{1004}{1075}-Dobro jutro, Gos. Clark.|-Jutro, Hunter.
{1945}{1995}-Haj, Carolyn. Haj, Scotty.|-Jutro.
{2000}{2074}Scotty, bi hotel odpreti vhodna vrata?|Pa pazi da ti ne padejo jajca na tla.
{2087}{2150}-Oèe jih potrebuje za eksperiment.|-Ok, mama.
{2276}{2338}Pomiri se, Buddy. Saj sem samo jaz.
{2382}{2405}Buddy, doma smo.
{2483}{2548}Pomiri se, Buddy. Saj sem samo jaz.
{2563}{2589}Buddy!
{2620}{2650}Oh, Buddy.
{2672}{2697}Buddy!
{2815}{2868}Buddy!!
{3819}{3874}Moja prelepa pita.
{5035}{5066}Poreden pes!
{5338}{5414}Pojdi ven, pojdi ven, pojdi ven!|Ven, zverina!
{6150}{6200}MAÈKE SO ZAKON
{6979}{7011}Kontrola tukaj.
{7016}{7050}Imamo resen problem.
{7483}{7577}Moj bog. Pošljite sem najboljšega|pasjega pretepaškega agenta. Gremo!
{7850}{7950}MAÈKI IN PSI
{8015}{8144}Gospodje. pred nekaj trenutki sem sprejel|sporoèilo, ki je zelo pomembne narave.
{8167}{8265}Kljuèni agent, kateri je delal na primeru Brody|je bil ugrabljen.
{8326}{8429}Èeprav je na varnem moramo dobiti menjavo|èimprej, ko je mogoèe.
{8452}{8534}Izgleda, da nam se|ponovno pojavlja...
{8539}{8608}...velika maèja pokora.
{8718}{8809}Sumimo, da je maèji malopridnež|umešan v zaroto...
{8814}{8918}... da unièijo, kar smo se psi|dolgo trudili, da smo dosegli.
{9045}{9119}Zato, v soglasju z planom Delta...
{9125}{9184}... smo izurili elitno skupino agentov...
{9190}{9282}... ki so trenirani da zamenjajo|naše ugrabljene tovariše.
{9288}{9380}V tem trenutku zamenjav|prihaja z letalom iz Londona.
{9392}{9465}Ta se bo pretvarjal, kot da je|Brody-jev ljubljenèek...
{9470}{9547}...in varoval njegov dom|pred maèjo invazijo.
{9587}{9689}Ni mi potrebno omenjati da je prihodnost|èloveka in psa...
{9693}{9779}...odvisna od uspeha |te misije.
{9784}{9870}Neuspeh ni dan kot možnost.
{9883}{9965}Stava je zelo velika.|Vse lahko zgubimo.
{9971}{10075}En milijon psov je|nam naložili svojo usodo...
{10079}{10151}...naravnost v naše šape.
{10348}{10398}-Ugriznil te bom v ušesa.|-Pojdi dol z mene!
{10433}{10487}-Bodeš me v oko.|-Prihajam skozi!
{10493}{10551}Oproste mi. Stopte na stran. Prihajam skozi.
{10559}{10614}Stran s poti. Oèistite prostor.
{10618}{10674}-Ne že spet.|-Kaj je tokrat?
{10694}{10766}Mislim da to ni dobra ideja.
{10782}{10822}Ne morem verjeti temu psièku.
{10834}{10866}Ko potegnem to vrv. . .
{10896}{10926}Kaj dela?
{10931}{11015}. . .bo vreèa padal na te vile,|katere pa me bodo ponesle skozi okno. . .
{11021}{11078}. . .in na pot do svobode,|torej umaknite se.
{11083}{11178}-Kaj je s tabo?|-Mano? Kaj je z vami?
{11221}{11334}Jaz hoèem avanture.Ne pa èakanja na nekoga,|ki me bo nesel v dolgoèasno hišo.
{11338}{11394}Kaj je narobe s družino,|ki te ljubi?
{11399}{11459}Brezplaèna hrana, topel kotièek za spanje.
{11466}{11546}In lahko greš na stranišèe|koder hoèeš.
{11566}{11622}Kaj noèete delati|nekaj razburljivega?
{11627}{11685}Kot biti policijski pes!|Ne?
{11695}{11804}Ali Ruski vesoljski pes!|Ali da poizkusiš varovane kosti Evrope!
{11823}{11870}Dajmo no, fantje.
{11874}{11967}Oh, pozabite.|Se vidimo kasneje zelenci.
{11990}{12040}Oh, fantje, jaz ne morem gledati.
{12046}{12074}To bo dobro.
{12079}{12114}Svet, prihajam!
{12227}{12270}Poglej, leti.
{12330}{12368}Ne, ne leti.
{12399}{12479}Si že nazaj iz tvoje avanture,|Scooby-Doofus?
{12485}{12514}Kje sem?
{12828}{12851}Kaj je to?
{12898}{12965}-Naj gre nekdo pogledati.|-Pojdi ti.
{13066}{13121}OK, prav! V to luknjo!
{13126}{13195}Gremo! Strogo zaupna operacija!|V luknjo!
{13199}{13236}Hitreje!|V luknjo!
{13240}{13328}Videl sem hitrejše èivave od tega.|Mahaj z repom!
{13631}{13704}Zdravo. Sem!
{13742}{13812}Na tla, Clucky!|To je ena jezna kura.
{13816}{13865}Sprednji in centralni, agenti!
{13870}{13921}Hop, hop, hop!|Gremo! Hitreje, dame!
{13925}{13977}Ravna kolona! Ušesa gor! Hitreje!
{13982}{14042}Ne prisile me da ti dam nagobènik!|Hoèeš žveèiti igraèko?
{14054}{14114}-Ali hoèeš vzburjenje?|-Gospod, tako je, gospod!
{14121}{14190}-Ali hoèeš avanture?|-Gospod, tako je, gospod!
{14194}{14235}Èe te bo izbrala gospodièna Brody. . .
{14241}{14310}. . .boš dobil navodila za varovanje.|Ali si pripravljen?
{14314}{14341}Gospod, tako je, gospod!
{14350}{14383}Sreèno.
{14415}{14479}To so najbolj pametni kužki,|ki ste jih do sedaj videli.
{14532}{14555}Sem.
{14573}{14660}Za božjo voljo,|ne pozabite mahati z repom!
{14707}{14770}Tako kot ste jih opisali|se mi zdijo popolni.
{14774}{14809}Tako so srèkani.
{15011}{15066}Zamenjali so višino. . .
{15080}{15110}. . .in barvo.
{15131}{15177}in pasmo.
{15539}{15599}Èudovit je.
{15627}{15669}Pozdravljeni!
{15675}{15765}In ti greš z mano domov.|Da, greš.
{15868}{15905}Ni dobro!
{16180}{16241}Draga? Takoj pridem.
{16271}{16322}Haj, ljubezen.
{16330}{16410}Imam preseneèanje zate.
{16446}{16471}Novega kužka!
{16495}{16559}Toda, mama, Buddy se lahko še vrne.
{16579}{16657}Oprosti, ljubèek.|Vem, da ga ni že en mesec.
{16662}{16752}Toda ali se spominjaš kako smo|bili sreèni ko smo našli Buddya?
{16758}{16863}Gotovo je našel in osreèil|kakšno drugo družino.
{16906}{16945}Poglej ga.
{16950}{17001}In oèe ga potrebuje za delo.
{17035}{17154}Lahko mu meèeš palice, lahko se igraš|s frisbijem in skrivalnice.
{17168}{17207}Da. Odlièno.
{17217}{17254}Daj da vidim.
{17262}{17343}Oh, da, da. Pusti mi da vidim.
{17364}{17387}Jeza.
{17393}{17416}Standardno.
{17434}{17483}Reakcija mrežnice. . . .
{17517}{17582}Normalno. Viskoznost nosu. . . .
{17609}{17721}Ni preveè kislo, ni preveè bazno.|Dobro, neobèutljiv odziv.
{17881}{17917}To je odlièno!
{17923}{17989}To je dobro! Sedaj. . .
{17993}{18075}. . .malo proteinske sinteze in | elektrostatike. . . .
{18115}{18138}Torej. . . .
{18150}{18232}Jaz vem. Zakaj mu ne bi dal imena?
{18244}{18309}Ok. Kaj pa "Zguba"?
{18344}{18378}On je pes, mama.
{18387}{18460}Ti nisi zguba, kajneda?
{18520}{18582}Poèakaj.|Lou.
{18595}{18636}Torej klicali te bomo Lou.
{18713}{18771}Niè igranja v dnevni sobi.
{18775}{18882}Preproga je iz Uzbekistana.|Deset tisoè vlaken.
{18975}{18998}Kaj?
{19131}{19162}Zguba.
{19167}{19198}Maèja oseba.
{19232}{19274}Ok, tukaj je naèrt:
{19278}{19355}Gremo skozi dvorišèe,|in nazaj v skedenj. . .
{19362}{19421}. . .vzamemo boljše vile.
{19661}{19695}Cool.
{19971}{20013}Jaz ne bi storil tega na tvojem mestu.
{20051}{20138}Rad imam tvoj pogum,|toda naredi mi uslugo in ostani zadaj.
{20141}{20176}To je moj piškot.
{20246}{20321}To naj bi bila najkrajša naloga|v zgodovini.
{20326}{20349}Kam greš?
{20362}{20438}Sklepam, da v štabu ne trenirajo veè|kot vèasih.
{20443}{20502}-Kdo pa si ti?|-Ime mi je Butch.
{20507}{20618}Kakšno neumno ime ti je nadel dvonožec?|Spot? Fifi? Rover?
{20631}{20667}-Lou.|-Bog pomagaj.
{20671}{20736}Oh, Lou. Oprosti.
{20742}{20834}Ali je ta poba vedno tako teèen?|Mogoèe bi morali menjati njegovo prehrano.
{20842}{20946}Ljudje postanejo malce èustveni.|Navadil se boš. Pridi. 
{21195}{21238}Od kje prihaja?
{21291}{21315}Cool.
{21318}{21365}Kaj? To je standardna oprema.
{21370}{21474}EC-3 video-telefon, raziskovalni arhiv| šifre, Snausages.
{21479}{21526}-Hej, kaj je to?|-Pekel!
{21534}{21622}To je veliki gumb.|Ne smeš pritiskati tako.
{21628}{21660}-Jezus.|-Oprosti.
{21666}{21710}Samo poskusi se spomniti tvojega urjenja.
{21751}{21803}Pa zaènimo. Evo suhca:
{21808}{21862}Tvoj novi gospodar je znanstvenik.
{21867}{21935}Dela na zdravilu proti pasjim alergijam.
{21940}{22050}To je velik posel. Èe nebo nihèe alergièen| na pse,bomo imeli prednost.
{22055}{22165}To je bil tvoj predhodnik:|Agent 1364, AIKA Buddy.
{22170}{22219}Bil je ugrabljen pred nekaj meseci.
{22224}{22284}Ni bil v najboljši formi.|Moral se je upokojiti.
{22290}{22354}Ima fino stanovanje v Boci.|sreèni pes.
{22358}{22394}Tukaj si kot njegova zamenjava.
{22399}{22465}In da držiš maèke proè od formule.
{22470}{22534}Ne smemo jih pustiti blizu.|Sedaj, pridite.
{22614}{22666}V redu, agent, spoznajmo ekipo.
{22694}{22752}"Agent"!|Vau, stari!
{22805}{22857}Poba, poglej tja.
{22863}{22907}-To je Peek.|-Peek?
{22931}{22959}Ne razumem.
{22968}{23019}Peek, pokaži se.
{23113}{23182}Imamo situacijo na vogalu|Centra in Glavne ulice....
{23222}{23252}Oh, moj bog!
{23283}{23322}Peekovo zgodnje opozorilo.
{23328}{23437}Ima vse. Radar, sonar,|termo-prikazovanje, prepoznavanje okusa.
{23443}{23540}Prepozna potepuške maèke|do tri ulice stran.
{23547}{23607}-Peek, vstopi.|-Razumem.
{23739}{23817}-Sam, kaj vidiš?|-18 stopinj na levi.
{23822}{23914}Izsledil jih bom s pomoèjo| delta prehoda tri...
{23919}{23970}. . .dva. . .ena.
{24060}{24100}Pozdravljeni fantje.
{24110}{24138}Oh, ne, ne že spet.
{24149}{24180}Kje sem?
{24342}{24371}Tukaj, Sam.
{24395}{24473}Prosim za dovoljenje za globoko sopihanje, gospod.
{24479}{24498}Odobreno.
{24549}{24607}Fantje, spoznajte Louja.
{24612}{24635}-Hej, Louie.|-Hej, Lou.
{24641}{24664}Èlovek!
{24930}{25003}Lou bo prevzel Buddyevo mesto.|On je v vroèem sedežu.
{25009}{25090}Svež iz akademije, On|pozna vse najnovejše tehnologije.
{25096}{25131}Kajneda, Lou?
{25174}{25269}A poznate tole? Prihajamo.|Imam te! Oh, zgrešil sem te.
{25278}{25319}Sveta èivava.
{25324}{25350}Kako se je zgodilo?
{25355}{25392}Po nesreèi se je izmuznil skozi.
{25400}{25472}Obljubili ste mi profesjonalca.| In kaj dobim?!!!KUŽKA!!!!
{25474}{25546}Še vedno ima saj veste kaj!
{25552}{25646}Ni èasa, Butch. Kužek ostane.|Konec pogovora. Konec.
{25830}{25875}Povej mi, eden izmed vas. . .
{25890}{25930}. . .ali je pes iz poti?
{25995}{26064}Ali je kužek padel v mojo pametno past?
{26109}{26178}Nihèe izmed vas nima zgodbe za povedati???
{26182}{26269}Majhno zgodbo zame, mogoèe?\?
{26313}{26378}Ti! Povej mi, ali je igra na nogah?
{26383}{26414}Ja?
{26419}{26489}-Zakaj je igra na poti?|-Mislim,ne.
{26494}{26529}Ah, odlièno.
{26535}{26597}Torej je kužek mrtev.|Sedaj se lahko premaknemo na--
{26602}{26631}Poèakaj,poèakaj.
{26636}{26674}Ali lahko spremenim svoj odgovor?
{26680}{26720}Ali je kužek živ ali ne?
{26725}{26778}Drug pes mu je povedal , da je bila bomba. 
{26803}{26849}Drug pes???
{26855}{26980}Kakorkoli preprièan sem, da bomo prišli v |kletni laboratorij. Imam prav, fantje?
{26984}{27039}-Fantje!|-Oh, da, seveda, ni problema.
{27043}{27089}-Absolutno.|-Vidiš?
{27094}{27165}Projekt temen oblak se mora izvesti| brezhibno.
{27169}{27255}Temen oblak?:)?|Ali tako klièete moj naèrt?
{27259}{27312}Ne da bi jaz vedel.|Ne, vi ga klièete. . . .
{27318}{27356}-Kaj pa Nevihta!|-Temna Nevihta.
{27361}{27406}Temna nevihta,da.
{27413}{27479}Da. Kot moèna, èrna nevihta. . .
{27485}{27552}. . .moja prisotnost bo znana celem svetu.
{27570}{27680}. . .kot meglica se bom spustil v|center pasje moèi in ..
{27688}{27794}. . .jih narediti prestrašene|ko bodo zaslišali moje ime!
{27807}{27847}Gos. Tinkles!
{27876}{27902}-Skrijte se!|-Hitro!
{27909}{27950}Kje si?
{27955}{27978}Skrijte se!
{27996}{28067}Tukaj si,Gos. Tinkles.
{28083}{28213}Povsod sem te iskala.|Kje si bil?
{28218}{28293}Gos. Mason bo sreèen, ko te bo zagledal.
{28310}{28360}Nesla te bom k njemu.
{28430}{28486}Ti si smrdeèa maèka.
{28492}{28551}Najprej te bom okopala.
{28581}{28651}Gos. Tinkles, ne pozabi|se umiti za ušesi!
{28682}{28807}Èe bom bil skrivni agent,|bi moral imeti boljše ime.
{28813}{28896}Razmišljal sem: Popolno unièenje
{28897}{28966}On je izkušen rokoborec.|To ime je zasedeno.
{28971}{29014}Potem bo "Unièevalna mašina" prava.
{29019}{29119}Lahko se klièeš|Squicky-vesoljski pes èe hoèeš.
{29134}{29188}To ne naredi tvoje riti|na raketni pogon.
{29194}{29289}Ti nisi agent,|toda pomagal nam boš.
{29320}{29393}Torej korak za korakom.|Otrok, poslušaj.
{29398}{29427}Zgodovina 101 :
{29431}{29491}Psi so bili vedno|Èlovekovi najboljši prijatelj.
{29495}{29530}Preprièan sem da to veš.
{29535}{29591}Toda maèke, one so druga zgodba.
{29599}{29636}Peek, zaèni z starodavnim Egiptom.
{29642}{29705}To smo videli že preveèkrat.
{29709}{29767}Okej. Ni važno.|Oprosti. Tukaj gre.
{29813}{29857}Starodavni Egipt.
{29897}{29940}Vidiš tele hieroglife?
{29946}{30026}Ljudje jih berejo in pravijo, da so|starodavni ljudje èastili maèke.
{30030}{30100}Toda v resnici so jim|maèke vladale.
{30110}{30232}In potem jih je zlobna maèka imenovana Shen-Akh-Akumma|pripravila do tega da so gradili piramide, kipe. . .
{30236}{30309}. . .in jim grozila kot, da so|njeno stranišèe.
{30315}{30366}Stvari so bile obupne.
{30372}{30395}To je najboljši del.
{30402}{30501}In tako so psi,|postali èlovekovi najboljši prijatelji.
{30543}{30608}In jih odstranili.
{30635}{30746}Ko so bili ljudje spet na vrhu, smo|prevzeli naš prostor ob njihovi strani.
{30759}{30799}In to so ljudje pozabili?
{30804}{30879}Paè  so zelo primitivna bitja.
{30883}{30938}Ne èutijo potresov, vohajo strahu.
{30943}{31029}Prekleto, niti ne prevzamejo|odgovornosti za njihove lastne prdce.
{31063}{31104}Debeli.
{31110}{31139}Kriv.
{31144}{31175}Jaz bom dobil ograjo.
{31190}{31247}Tako se je naša oblika zaèela.
{31253}{31365}Vèasih kakšna potepuška maèka postane prevelika za|njen plašè in misli, da lahko vse prevzame.
{31370}{31464}Naša misija je ,da obdržimo maèke stran od|laboratorija dokler ne konèa formule.
{31499}{31568}-Karkoli èudnega v hladilnici.|-da,gospod!
{31573}{31623}-Kakšno vprašanje?|-Samo eno, gospod.
{31628}{31678}-Ustreli.|-Kaj je starodavni Egipt?
{31736}{31770}Zamrzni,maèek.
{31777}{31806}jaz sem agent.
{31813}{31870}Tako sem hiter, da se ne vidim.
{31886}{31942}Agent "Unièevalna mašina". Tako je.
{31950}{32012}Pazi se, maèka.|Niti videti ga nisem mogel.
{32018}{32080}Tam je priden kuža. Zdravo!
{32084}{32146}Ne bodi prestrašen. Ne bodi prestrašen.
{32151}{32233}Poglej kako dober si.|Poglej kako dober.
{32240}{32298}Kje je to--? Tam. Imam jo.
{32304}{32340}To nebo niè bolelo.
{32460}{32526}Pa poglejmo. Pa poglejmo.
{32684}{32729}Hej, to je dobro.
{32930}{32966}-Hej, oèe!|-Bolonèki.
{32970}{33007}Ali mi boš pomagal trenirati? 
{33085}{33107}Ne. Ne.
{33190}{33260}Pozneje se bova igrala.|Obljubim.
{33675}{33757}Pozabil sem tvoj lok.
{33762}{33852}Oh, tvoj ljubek lok.
{33879}{33960}Ko bom vladal zemlji, boš prvi. . .
{33966}{34004}. . .na mojem list.
{34014}{34071}Drži tako svoje dlake.|Shujšane so.
{34077}{34122}Na listi je prostor tudi zate.
{34125}{34162}Ne, resno mislim.
{34200}{34240}Imamo samo par dni za uspeh.
{34244}{34363}Èeprav  je igranje za tega bolnega starca|zgoraj kljuè za mojo shemo. . .
{34369}{34474}. . .Ne prenesem tega poniževanja| niè veè. Ali sem jasen?
{34510}{34588}Pozabi.|Kužek ne bo preživel te noèi.
{34593}{34626}Pošljite "ninje". 
{34774}{34821}Nervozen zaradi jutranje preizkušnje?
{34834}{34863}Ne.
{34869}{34951}-Dobro je èe si živèen.|-Nisem živèen.
{34957}{35021}Smrdim toda nisem živèen.
{35027}{35146}Ali govori to zaradi tega, da naj ga pomirim?
{35167}{35222}Da. Pomiri ga.
{35234}{35336}Ti si najbolj èudovit,|najveèji, šarmanten, dobri formi. . .
{35374}{35441}. . .poba na celem svetu.
{35478}{35583}-Mogoèe ti lahko oèe pomaga.|-Ne, sem zelo preprièan, da tudi on smrdi.
{35594}{35640}Govoril bom z njim.
{35677}{35715}Èas z posteljo. Izkljuèi TV.
{35721}{35764}-Pet minus.|-Sedem.
{35798}{35857}-Ljubim te.|-Jaz tebe tudi.
{35866}{35908}No? Izroèi.
{35914}{35985}Kaj?! Ni preliva?
{36045}{36098}Naslednjiè ne pozabi preliva.
{36116}{36150}Psi so zakon.
{36177}{36232}Ali kam greš?
{36240}{36305}No, pa poglejmo.
{36309}{36412}Ooh, jah. 1409 Maple Terrace.
{36420}{36455}Imam ga.
{36466}{36561}Totalna prikrita operacija.|Moraš biti neviden.
{36925}{36953}Hej, Sam.
{37209}{37290}Na moj znak. Tri, dva, ena.
{37295}{37350}Banzai!
{37554}{37579}Lou, Peek je.
{37585}{37631}Lou. ali si tam? Peek je.
{37654}{37700}Kaj? Kaj? Kaj?
{37706}{37751}Vidim slab signal.
{37758}{37839}Mogoèe je odsev.|Bolje da preveriš.
{37846}{37885}Okej. Grem pogledat.
{37892}{37932}Bodi previden, poba.
{37952}{37986}Jaz sem agent.
{37999}{38041}Jaz sem skrivni agent.
{38059}{38118}Jaz sem en-pes vojska.
{38719}{38761}Obrni se.
{38957}{39004}Hrošè aktiviran.
{39253}{39326}Peek? Halo? Peek?
{39341}{39370}Videti je èisto.
{39374}{39454}Verjetno samo veverica.|Sporoèil bom Butchu.
{39669}{39716}-Butch, kaj naj naredim?|-Ugrizni jih.
{40235}{40258}Kaj?
{40556}{40592}Samo naredi kot ti reèem.
{40596}{40631}Leva! Desna taca! Še enkrat!
{40699}{40728}Obrni se!
{40746}{40793}Dober pes. Tace gor!
{40825}{40855}Oslova brca!
{40869}{40921}Pridi poba, daj posvetim jim!
{41113}{41202}Premislil sem se.|Klièite me Ling Chowave šape!
{41208}{41241}Ling Chow tole!
{41311}{41356}Poèistite prehod 7.
{41390}{41422}Ljudje! Umaknite se z èastjo.
{41429}{41463}Imam kij.
{41479}{41541}Imam športno rokavico,|in se je ne bojim uporabiti.
{41857}{41892}Poreden pes.
{42050}{42101}Ti si sreèen, ker si tako srèkan.
{42354}{42405}-Unièevalna mašina.|-Hej, fantje.
{42413}{42502}-Še vedno si živ.|-Jep. Vseh pet okonèin.
{42512}{42576}Dolguješ mi pet prekajenih prašièjih uh.
{42582}{42641}Še vedno stojiš.|Ali si dobro?
{42646}{42729}Ali si me videl?|Desna, leva in desna in leva--
{42734}{42817}Postal si domišljav.|Misliš, da je to igra?
{42823}{42904}Ni vse v kodnih imenih,|majhni fantje, ali prijatelji.
{42909}{42988}Vse je v straži tega laboratorija.|Niè drugega.
{43005}{43074}Sam, Peek, zaprita tale dimnik.
{43554}{43589}Maèke.
{43642}{43689}Ali nikoli ne odnehate?
{43940}{43990}Hej!!!|Hej.
{44000}{44030}Ti pokažem nekaj èudovitega?
{44166}{44220}Brodijevi imajo najboljše smeti.
{44225}{44275}-Pojdite naprej. Vzemi ugriz.|-Joj mene.
{44298}{44366}Tole dobijo za hrano?|Kakšen slepar.
{44369}{44410}Vesela sem, da ti je všeè.
{44415}{44510}-Mislil sem, da sem že predolgo klatež.|-Klatež? Cool.
{44515}{44562}Nikoli še nisem sreèal klateža.
{44568}{44634}Pravzaprav, bolj cenim|"problem v hiši."
{44638}{44709}Gospa Izzivalna, oprosti,|toda moram iti.
{44716}{44773}-Moji ukazi so jasni. Ne morem-| -Ukazi?
{44779}{44826}Da. Jaz sem skrivni agent.
{44843}{44870}Agent?
{44875}{44969}Majhen si za agenta.|Ali se ne bi moral igrati?
{44974}{45010}Nimam èasa.
{45050}{45095}Žilav deèko.
{45173}{45235}Nehaj z tem agentskim sranjem. Okej?
{45250}{45369}Ti imaš svojega otroka, da se igraš z njim.|Ne jemlji ga zares.
{45478}{45546}Kam greš?|Ali lahko to narediš še enkrat?
{45550}{45657}Naslednjiè ko bo poba govoril s tabo,|nagni svojo glavo in dvigni ušesa.
{45663}{45719}Videl boš o èem govorim.
{45739}{45844}In naredi mi uslugo.|Povej Butchu, da je Ivy nazaj v mestu.
{46054}{46102}Kaj me gledaš?
{46140}{46222}Mislim, da si nekako srèkan.
{46291}{46350}Poglej kdo je. Imam te.
{46415}{46506}Prejšnjo noè sva s tvojo mamo imela pogovor. . .
{46512}{46564}. . .ki me je pripravil do tega. . .
{46570}{46623}. . .da bi se midva morala pogovoriti. . .
{46629}{46695}. . .o tebi in mojem projektu.
{46699}{46746}Ali hoèeš sesti?
{46781}{46819}Oh, jeh. Seveda, seveda.
{46859}{46911}Tvoja mama me je pripravila do tega. . . .
{46929}{47024}No prišel bom na tvojo|nogometno tekmo to popoldne.
{47030}{47071}Ne, ni ti treba.
{47077}{47100}Toda. . . .
{47173}{47196}Res?
{47208}{47237}Okej.
{47242}{47268}Ihuu! Okej.
{47276}{47334}-Oh, bog. Cool. Cool.|-Cool.
{47341}{47412}Noèeš biti pozen za šolo.
{47438}{47474}Jeh, sem.
{47487}{47540}-Se vidiva, Oèe.|-Se vidiva.
{47545}{47634}Gremo, gremo, gremo! Navijal bom zate!
{47639}{47761}Naša ekipa je rdeèe-vroèa|Tvoja skupina je brez vezna.
{48103}{48161}Bil sem slab. Slabši kot slab.
{48166}{48230}Scotty? Ali si videl tole majhno--
{48237}{48260}Trening!
{48378}{48427}Vov. On je zares slab.
{48466}{48522}Mislim, da mi ni šlo najbolje, huh?
{48525}{48564}Kaj je rekel trener?
{48610}{48697}Rekel je da je trening za dekleta|v ponedeljek.
{48747}{48785}Kaj je bilo pa z oèetom?
{49186}{49231}-Nogomet.|-Sem v sredi--
{49236}{49309}-Nogomet.|-Ne, hvala. Moram iti--
{49315}{49346}Nogomet.
{49403}{49487}-Pozabil sem. Imel sem preboj-| -Vem da si zaposlen. . . .
{49493}{49532}On je tvoj sin.
{49546}{49608}Imel sem preboj.
{49678}{49750}Vem. Vem. Žal mi je.
{50545}{50591}Dober poba.
{50600}{50632}Lep razgled.
{50646}{50688}Rekel si, da ne bova veè govorila.
{50694}{50767}-Sedaj imam razlog.|-Prihrani mi predavanje,vsaj tokrat.
{50779}{50900}Je samo kužek, Butch.|Ne ve v kaj se je zapletel.
{50886}{50994}Oprosti mi ker sem ga poduèil|o boljših straneh praskanja po trebuhu.
{50999}{51046}Zdaj , me èaka delo.
{51051}{51146}Nikoli se nisi pritoževal|kadar sem te praskala po trebuhu.
{51162}{51221}Pod luno?|Pred misijo?
{51226}{51291}Bi me klical Lamb Chop|in zardel. . .
{51296}{51358}. . .kadar bi ti rekel Liver Snap.
{51405}{51450}Pogled v zgodovino...
{51454}{51540}. . .je lajanje pod napaènim drevesom.|Samo enkrat bom to rekel:
{51547}{51621}Ne približuj se fantje.
{51684}{51766}Gos. Mason, nekdo bi|rad govoril s tabo.
{51790}{51873}To je èas Gos. Tinkleja, Gos. Mason.
{51934}{52029}Nocoj je obleèen v nekaj|posebnega.
{52033}{52069}Tukaj.
{52075}{52203}Te to kaj osreèi, Gos.. Mason?|Si zdaj sreèen?
{52535}{52645}Vidiš kako sreènega si naredila?|Srce mu je poskoèilo.
{52651}{52719}Pustil vaju bom skupaj.
{52839}{52914}Zlo ne nosi pokrivala!
{52948}{52971}Ali je šla?
{52977}{53102}Ali je Genghis Khan nosi pokrivalo?|Attila the Hun? Ne.
{53107}{53178}Nosi èuden klobuk.|Mogoèe èrno pokrivalo?
{53226}{53302}Ninje niso uspele.|Neuspeh je nesprejemljiv.
{53315}{53395}Èe se prikažejo,|veš kaj moraš narediti.
{53399}{53489}Povej jim naj se umijejo z| gobo. Šalim se.
{53495}{53581}To se ne more dogajati.|Hoèem jih mrtve!
{53613}{53651}Toda uspeli so nastaviti|"hrošèa" v telefon. 
{53641}{53729}Mogoèe lahko pogledamo v kozarec|kot napol polni.
{53754}{53796}Tole hoèem narediti.
{53802}{53899}Postavi smešen obraz na stvari.|Zanimiva filozofija.
{53910}{53985}Ali si pozabil, da prevzemamo svet?!
{53990}{54022}Ura tiktaka.
{54027}{54098}Mi smo zadnja meja za zmoto.|Jutri. . .
{54104}{54195}. . .boš poslal Ruse.
{54275}{54308}Poklical te bom nazaj.
{54566}{54645}Motnje zaznane|V strogo-zaupni galeriji...
{54650}{54682}...raziskovalnem laboratoriju.
{54715}{54753}Bavbav v žici.
{54759}{54791}-Ga imaš?|-Ne.
{54798}{54821}Hitro se približuje.
{54827}{54879}Niè ne vidim.|Megla je.
{54888}{54949}Tvoje dlake so, Sam. Raznesi.
{54976}{55042}Drži se. Mama je nazaj.
{55091}{55126}Oh, ne.
{55131}{55175}Poglej malo maèko.
{55181}{55256}Poglej malo maèko. Oh, ja.
{55261}{55313}To je dober deèko.
{55318}{55373}Je samo mali izgubljena maèka.
{55379}{55467}Obdržali ga bomo.|Da bomo.
{55472}{55519}Ne pojej ga.
{55590}{55649}Oh, poglej. Vidiš?
{55655}{55702}Poglej kako te ljubi.
{55707}{55766}Dave, zaletel sem se v štor.
{55770}{55865}Razkazati boš moral hišo|brez mene. Oh, poèakaj.
{55906}{55988}Kaj je to?|Je to kosmata kepa?
{55994}{56097}Prinesel ti bom vodo.|Ne še, Dave. Kmalu bom tam.
{56115}{56146}Poèakaj.
{56210}{56263}Sem že nad tabo.|V težavah si.
{56269}{56341}Jaz pa ne mislim tako, otroèji kužek.|Ti si v težavah.
{56416}{56462}Jaz pa že ne!
{56567}{56622}Iz Rusije z ljubeznijo.
{56632}{56656}Skrivnostni kakec.
{56767}{56822}Nimam èasa za to.
{56834}{56863}Poreden pes.
{56896}{56925}Kaj pa imamo?
{56931}{57005}-Rusko modro.|-in številko 2 v sektorju 3.
{57013}{57073}Ta parnik je veèji kot jaz.
{57080}{57133}Dobro delo.|Oddahni se malo.
{57138}{57198}-Ali je odšla?|-Ne vidim jo.
{57204}{57267}Bilo mi je podtaknjeno!|Poèakaj, hoèem pomagati.
{57279}{57348}-Poglej ven. Koda 4.|-Pohiti, povohaj moj ta zadnjo.
{57376}{57424}Dobro, dosti je bilo.
{57451}{57480}Hladen smrèek!
{57590}{57639}Kos nièvrednih Ameriških vrat.
{57774}{57872}Ne morem verjeti, da delam to|za polovièno ceno.
{57877}{57995}In ta Tinkles je kreten.|Govori preveè in meèe vse povsod.
{58001}{58037}-Premikaj se hitreje.|-Premikaj se zahodno.
{58043}{58122}-Premikaj se zahodno-zahodno.|-Na poti v vogal.
{58127}{58182}-Ven je .|-In ven je.
{58353}{58400}Oh, èlovek, zaklenjeno je.
{58459}{58556}Kaj pa vejo? Jaz delam trdo,|da dobim Wiskas.
{58611}{58646}-Kaj dela?|-Deèko!
{58654}{58683}Kaj? Psi!
{58789}{58819}Vzemi to!
{58894}{58927}Zgrešil.
{58973}{59003}Beži!
{59008}{59038}Pridi, deèko. Pohiti!
{59221}{59268}Pazi se! Prihaja!
{59426}{59504}-Bombam je postavljena na vratih od|laboratorija.-Uredili bomo to.
{59514}{59575}Psièki, zakaj ne pridete ven in se igrate?
{59581}{59629}-Fantje!|-Daj, èlovek!
{59635}{59670}Bomba. Bomba!
{59676}{59719}Jaz bom poskrbel za bombo.
{59839}{59886}- Zmoti ga.|-Zakaj jaz?
{59892}{59957}-Kaj nisi rekel, da hoèeš pomagati?|-Pohiti! Pohiti!
{59986}{60045}-Neumna maèka!|-To bo pridobilo njegovo pozornost.
{60488}{60546}-Predalnik bo padel.|-Ne, ne!
{60610}{60668}Butch. Bomba.|Imaš 45 sekund.
{60681}{60716}Delamo na tem.
{60741}{60786}Ne moreš jih jeziti.
{60827}{60849}Bumerang!
{61003}{61040}Pazi, deèko!
{61087}{61135}Dober ulov.
{61249}{61282}Èlovek!
{61643}{61669}Telefon.
{62158}{62195}Drži se, Butch!
{62202}{62240}Hej, kužek, ulovi.
{62245}{62275}Ne! Èakaj!
{62280}{62314}Prav!
{62436}{62488}Leteèi pes.
{62573}{62603}Drži se, deèko.
{62607}{62635}-Pohiti!Bomba!|-Bomba.
{62640}{62698}-Pojdi z dol z mene, krznena|žoga !-Boj!
{62707}{62761}Vzemi jim.|Jaz grem de-aktivirati bombo.
{62767}{62795}Deset sekund.
{62802}{62842}Udarjaš kot pudel.
{62846}{62898}Po knjigi sodeè naj bi najprej|prestrigel rdeèo žico.
{62903}{62958}Mi smo psi. Mi ne razlikujemo barve!
{62962}{63023}Tako je.Temno sivo!|Oh, no.
{63030}{63065}Ne dotikaj jo!
{63071}{63097}Pridi.
{63103}{63123}Prosim!
{63130}{63173}Ta je!
{63364}{63422}Ali mislite da ste zmagali?|Daljinski upravljaè !
{63541}{63576}Oh, bog.
{63582}{63623}Pridi sem, Lou.
{63629}{63712}-Dobra preobleka.|-Pridi sem.
{63718}{63756}Joj!
{63771}{63802}Drži se. dobri pes.
{63949}{63982}Nabreklo je.
{63988}{64014}To je odkritje.|Èe bi lahko našel. . . .
{64019}{64128}. . .malo proteina in|elektrostatiènega naboja. . .
{64135}{64181}. . .bi potrebovalo vsebovati|zmes. . . .
{64218}{64314}Dobro delo z bumerangom.|Zdaj se obnašaš kot agent.
{64331}{64417}-Ali je to kompliment?|-Meni nikoli ne daje komplimentov.
{64450}{64517}Sam, Peek, poklièita skupino za èišèenje.
{64590}{64704}Halo? Sem, mucek, mucek.
{64721}{64780}Sem, mali mucek, mucek.
{64790}{64884}Imam dobrote zate.|Sem, muci, muci--
{64950}{64991}Oh, moj bog.
{64997}{65069}Kdo je pustil odprta okna?
{65178}{65202}Sem,muci.
{65208}{65270}Niè vam ne bom povedal!
{65300}{65366}Mogoèe izgledam krut in grd ...
{65360}{65430}. . .toda znotraj, granit!
{65440}{65506}Niè veè ne moremo iztisniti|iz njega.
{65510}{65575}Izèrpali smo mu par stvari|iz trebuha.
{65579}{65604}Zelo standardno:
{65610}{65674}Bombe, šilo,|razstrelivo, vrešèeèo miš...
{65679}{65702}...in to.
{65708}{65795}"To je tukaj kjer ti odigraš|moj peklenski naèrt.
{65799}{65881}Pojej to ko boš prebral,|da ga ne bo mogel nihèe najti."
{65891}{65950}Poglej sem. Božièno drevo.
{65969}{66025}Poskušajo da odkrijejo|položaje.
{66030}{66056}Obroè in zvonci?
{66124}{66150}Kaj je naslednje?
{66155}{66228}Slišali ste jo, fantje.|Osredotoèite se na misijo.
{66247}{66326}-Preglej pregrade vsakih 20 minut.|-Razumem.
{66332}{66402}-Sam, uredi obroèek.|-Oprosti.
{66408}{66454}Poba, Nadaljuj z dobrim delom.
{66459}{66518}Zapomni si, da boš ostal stran od fanta.
{66524}{66566}Osredotoèi se na žogo.
{66574}{66653}Daj no! Kje je žoga?|Prinesi mi žogo!
{66685}{66741}Daj no, prinesi mi žogo.
{66747}{66788}Kje je žoga?
{66793}{66828}Daj no, Lou.
{66833}{66879}Prinesi mi žogo, Lou!
{67188}{67254}Sedaj ga imam!|Ne moreš je dobiti zame!
{67719}{67786}Kako da me zmeraj najdeš?|Povej mi.
{67789}{67818}Da slišimo.
{67859}{67908}Drgnjenje po trebuhu!
{68038}{68089}Izzivam te na dirko èez dvorišèe!
{68093}{68132}Kaj? Prepoèasi?
{68149}{68242}Daj no! Ne moreš me ujeti!|Poskusi in dobi jo.
{68298}{68322}Oh, ne!
{69170}{69193}Ne, Lou!
{69528}{69582}Negativno. Ne-delujoè.
{69596}{69671}Vzorec seruma 1-5-4-3...
{69688}{69735}...negativno. Ne-delujoè.
{69742}{69765}Moje delo.
{69771}{69881}Bila je nesreèa. Igral sem se z|psom..vrata so bila odprta!
{69886}{69942}Potem sem se samo igral. . . .
{69946}{69998}Nisem mislil.
{70002}{70094}-Oprosti mi.|-Moral bi iti v šolo.
{70099}{70200}Vzorec 1-5-4-6 negativen.|Ni reakcije.
{70206}{70242}Butch me bo ubil.
{70248}{70362}1-5-4-7, negativen.|Ni reakcije.
{70382}{70452}vzorec seruma 1-5-4-8...
{70474}{70538}...negativen. Ni reakcije.
{70542}{70636}Vzorec seruma 1-5-4-9...
{70642}{70716}...pozitiven. Reakcija.
{70732}{70850}Molekularna struktura narejena.|Alergenaska formula konèana.
{71319}{71354}Uspelo mi je.
{71374}{71406}Uspelo nam je.
{71410}{71451}Uspelo nam je.
{71553}{71646}Zdravo, doktor. Zdravilo proti pasji alergiji?|Uspešno. Narejeno.
{71650}{71725}Fantastièno. Pošljite mi jo|in mi jo bomo potrdili.
{71730}{71786}Se vidimo jutri zjutraj.|Bog z vami.
{71798}{71831}Nesprejemljivo.
{71836}{71918}Ukrepati moramo sedaj|ali pa bo izven obsega.
{71940}{71977}Veš kaj to pomeni?
{71978}{72000}Oh, kdo? Jaz?
{72005}{72058}Spet ne slediš pogovoru?
{72062}{72130}-Niti ne. Ali si razjarjen?|-Da! Razjarjen sem!
{72136}{72171}Ti imbecilna žuželka. . . .
{72177}{72207}Gos. Tinkles!
{72290}{72359}Ugani kaj sem naredil zate!
{72493}{72563}Sedaj lahko izgledaš natanko tako kot jaz.
{72569}{72673}Ne, mislim da ne, Sophie.|Tile dnevi so mimo.
{72700}{72755}Kaj je narobe, Large Marge?
{72761}{72800}Ti je muca snedla jezik?
{72750}{72904}Buu!!|O moj bog?! Govoreèa maèka ?
{72905}{72934}Strašljivo, ali ne?
{73046}{73120}Zakleni jo v omaro.|Nadaljuj po naèrtu.
{73127}{73164}Naš dan je prišel!
{73350}{73373}Zaviraj!
{73477}{73500}Plin!
{73543}{73583}Zaviraj!
{73665}{73700}Ali bomo prišli skozi|na tak naèin?
{73710}{73750}Glej me.
{73859}{73918}Gos. Mason.|Kakšno preseneèenje, gos.
{73926}{74021}Dobro jutro, varnostnik.|Spusti nas noter. To je vse.
{74035}{74060}Seveda, gos.
{74070}{74100}Fantje spodaj. Pohodite gas.
{74125}{74164}Spusti zavoro!
{74335}{74364}Zaviraj!
{74398}{74433}Zaviraj! Stisni zavoro!
{74458}{74488}Plin!
{74493}{74529}Stran s ceste!
{74535}{74570}Zaviraj!
{74576}{74623}-Plin!|-Kaj pa delaš?
{74666}{74728}-Zaviraj!|-A ne znaš vozit, preklet imbecil?
{74734}{74769}Ne izzivaj, èe ne bom prišel gor--
{74776}{74818}Kdo ti je dal izpit?
{74862}{74909}Halo. Stran s poti.
{74958}{74997}Pozor, uslužbenci.
{75003}{75096}Delajte hitro.|Samo še sedem mesecev do Božièa.
{75102}{75159}-Gos. Mason!|-Dajmo. Nazaj na delo.
{75164}{75201}-Gos.|-Zaèni živeti.
{75207}{75262}Stran s poti.|Zate ne bo malice.
{75267}{75290}Gos. Mason!
{75296}{75338}-Jutro, gos.|-Zakon kapa.
{75352}{75389}-Kako se poèutite,gos?|-Gremo.
{75398}{75440}-Halo, gos.|-To sem jaz.
{75445}{75526}Ne tista zlobna maèka, ki namerava|zavzeti svet.
{75532}{75567}Stran s poti.
{75600}{75668}Tovarniški delavci, èestitam.
{75672}{75772}Ta tovarna je|varna še 45 minut.
{76033}{76083}Gos! Gos. Mason.
{76135}{76162}-Gos.|-Odpri vrata.
{76291}{76338}Lepa obleka.
{76407}{76473}-Ti lahko kaj prinesem?|-Sushi in sladoled.
{76478}{76511}Zapri vrata.
{76581}{76616}Pozor.
{76645}{76692}Pozor, èloveški delavci.
{76698}{76742}To je tvoj delodajalec...
{76748}{76771}. . .Gos. Mason.
{76776}{76854}Uèinkovito takoj,|vsi ste odpušèeni.
{76859}{76906}Tako je. Odpušèeni!
{76911}{76976}Pojdite domov. Ne vprašajte zakaj.
{76983}{77026}Ti si kriv.
{77031}{77092}Razen, èe nimaš psa.|Potem obtoži njega.
{77119}{77181}U bistvu, brcni ga ko prideš domov.
{77187}{77213}To je vse.
{77269}{77299}Maèke so zakon.
{77306}{77362}Zadaj, naslednja faza mojega naèrta.
{77586}{77626}Scotty?
{77631}{77681}Paket imam zate.
{77802}{77891}Poèakaj. Kam je šla?|Noter ali ven? Noter ali ven?
{77896}{77937}Draga, draga.
{77968}{78042}Ne boš verjel.|Preboj.
{78050}{78115}Ure sem stran od--
{78137}{78187}Mama, Oèe! Preveri!
{78194}{78238}Karte za današnjo igro.
{78286}{78334}-Kaj?|-To je super.
{78339}{78382}Uruguay proti Chadu.
{78388}{78435}Nikoli nisi prišel v dvoboj.
{78442}{78500}Lahko gremo? Prosim?|Prosim, ali lahko gremo?
{78561}{78589}Jaz?
{78639}{78710}Prosim, res bi rad šel. Pridi.
{78787}{78858}Pohiti, pripni se!|Noèem da zamudimo!
{78863}{78919}Okej. Hej, že vem.
{78954}{79024}-Ptice so zapustile gnezdo.|-Še enkrat.
{79028}{79088}Marmelada je izven krofa.
{79092}{79174}-Kaj si rekel?|-Družina ni veè.
{79189}{79227}Hej, Lou.
{79268}{79330}Ti si. Kje si pa bil?
{79336}{79361}Okoli.
{79367}{79451}Ta teden je bil neverjeten.|Moram pretepsti mucka.
{79458}{79484}Sem na tekoèi hrani.
{79502}{79583}-In Scott je rekel, da sem njegov najboljši prijatelj.|-Izvrstno.
{79590}{79622}Ne povej nikomur.
{79625}{79710}Butchu to ne bi bilo všeè.|Postane jezen.
{79716}{79783}Da, vem. Ampak ni jezen.
{79788}{79859}Kdaj pa kdaj je jeza |izražanje ali skrivanje. . .
{79867}{79962}-. . .kako žalosten si.|-Kaj? Zakaj bi bil žalosten?
{80021}{80128}Nisem jaz pristojen da bi to rekel.|Ampak neka oseba ga je res prizadela.
{80162}{80218}Ubogi Butch.
{80302}{80370}Tukaj smo.|Sem rekel da nas bo spravil sem.
{80374}{80477}Upam da Mbuto igra.|On je najboljši napadalec z eno nogo.
{80482}{80582}-Je to pravo mesto?|-Kje so kontrolorji kart?
{80658}{80721}Smo prezgodnji? Nobenega ni okoli.
{80725}{80800}Zaradi tega bomo prvi v vrsti|za Mrzlega psa.
{80838}{80895}Mrzel pes! Mrzel pes!
{80901}{80948}Koliko sem ti dolžan?
{80970}{80982}Oprosti mi. Nisem ulovil.
{81046}{81081}-Halo.|-Brez obremenitev!
{81141}{81175}-Kaj!|-Kaj je?
{81181}{81234}-Oh, moj Bog!|-Vzemi nazaj.
{81690}{81747}Maèke so zakon, maèke so zakon.
{81791}{81826}Oh, da, brcamo riti
{82052}{82087}Deèko.
{82103}{82132}Lou!
{82165}{82196}Butch.
{82204}{82232}Kako je?
{82247}{82328}Profesor je pripravljen,|izpolnil sem poroèilo in. . . .
{82350}{82376}Fant. . .
{82387}{82429}. . .impresionirani so.
{82452}{82508}Hoteli so naj ti dam tole.
{82610}{82643}Ampak to je zate. . . .
{82647}{82732}Ko bo tega dela konec,|imaš mesto na akademiji.
{82737}{82797}Uspelo ti je, deèko.|Dobro opravljeno.
{82802}{82870}Bom postal pravi agent kot ti?
{82877}{82906}No, lahko poskusiš.
{82909}{82966}-Partnerji!|-Ne zmoèi še papirja.
{82972}{83061}Ampak èe ti uspe,|pomisli na vse kraje ki jih boš videl.
{83081}{83157}Mogoèe Burma. Da.
{83165}{83222}Ali Danska. Kako ji je bilo ime?
{83242}{83280}Ali Pasadena.
{83301}{83382}Poèakaj. Torej jaz ne bi ostal tukaj.
{83386}{83440}Šel boš kjer te bodo potrebovali.
{83485}{83525}-Bavbav na vidiku.
{83558}{83615}Bombažna tkanina je.|Ali naj jo vzamem?
{83621}{83677}Negativno. Jaz in deèko sva dojela.
{83686}{83709}Da!
{83714}{83822}Moje zadnje delo. Dostavi to kaseto,|in grem na Jamajko.
{84047}{84097}-Kaj je to?|-Pojdi dol z mene.
{84103}{84155}Okej, saj si me.
{84161}{84232}Stop. Prosim ne potegni|za lepilni trak!
{84261}{84296}Halo. Je to vkljuèeno?
{84302}{84374}Bližje! Obrni!|Od kje si pa ti prišel?
{84378}{84466}Hello, moji neumnim|pasje obrazni nasprotniki.
{84470}{84516}Kaj? Da, vklopljeno je.
{84522}{84565}Rdeèa luèka utripa.
{84703}{84755}Preprièan sem da si zaèuden...
{84758}{84846}...glede identitete sovražnika|ki te bo premagal.
{84851}{84930}Kdo je ta ki posreduje|to zmagovalno inteligenco...
{84934}{84996}...v tej partiji šaha|pameti in moèi.
{85010}{85050}To sem jaz!
{85074}{85118}Prepoznate te ljudi?
{85133}{85207}Èe jih hoèete videti|žive še zadnjiè...
{85212}{85276}...prinesite formulo|in vsa navodila...
{85282}{85405}...glede Brodijeve raziskave|na Deveto Pierjevo Ulico do polnoèi.
{85410}{85510}Èe zavrnete, no, jih| bomo uspavali!
{85566}{85595}Drži to na miru!
{85600}{85662}Imeli boste èas do polnoèi da privolite.
{85706}{85798}-Saj jih bodo rešili, kaj ne?|-To je nad vašimi glavami.
{85979}{86072}-Ali klièete štab?|-Ne, šli bomo tja.
{86075}{86138}Zdaj lahko pritisnemo ta velik gumb.|Držite se.
{86195}{86230}-Navigacijski sistemi.|-Preverjeno.
{86251}{86295}-GPS.|-Preverjeno.
{86300}{86367}Dvigovanje sider. Pripravljeni za izstrelitev.
{86372}{86427}Primi se za rep, deèko!
{86602}{86658}Hitrost 625 èevljev na sekundo.
{86678}{86743}Ste pripravljeni za EVO.
{86908}{86975}Canine transport|nalaganje na platformo dva.
{86981}{87063}282. Airborne Chihuahuas,|javite se v pisarni.
{87068}{87154}To je to, deèko. Dobrodošli v štabu.
{87158}{87193}Obrni se!
{87237}{87271}Obrni se! Sedi!
{87275}{87369}Sprejanje in neutraliziranje | preobratne procedure na tretjem nivoju.
{87621}{87716}-Za obrambne namene , seveda.|-Oh.
{87723}{87758}Seveda.
{87761}{87835}Od udeležencev se zahteva da |se brzdajo.
{87840}{87892}Ne pozabite zakopati svojega sranja.
{87899}{87936}Testiram, testiram.
{87942}{88005}Prišel si do štaba.|Priklopi se.
{88011}{88054}Tiger, kaj poèneš?
{88092}{88118}Poreden pes!
{88212}{88251}Prepoznate te ljudi?
{88258}{88350}Èe jih hoèete videti še enkrat,|prinesite formulo...
{88354}{88446}...in vsa navodila|glede Brodijeve raziskave...
{88451}{88566}... na Deveto Pierjevo Ulico|do polnoèi. Èe zavrnete...
{88569}{88636}... jih bomo uspavali.
{88651}{88690}Sestavite odposlanstvo.
{89034}{89077}Mir! Mir, prosim.
{89082}{89128}Odposlanci, prosim! Mir!
{89216}{89318}Ne moremo jim dati formule.|Žrtvujte Brodijevo družino.
{89324}{89424}Ne! Življenja so ogrožena.|Ne moremo jih soditi da so pogrešljivi.
{89432}{89505}Odposlanstvo, prosim! Mir!
{89510}{89548}Moram imeti mir!
{89562}{89598}Prosim, brez leteèega krožnika!
{89658}{89709}Steve, kontrola množice.
{89907}{89939}Sedi!
{89970}{90038}No zdaj, odposlanci.|Èas je za volitve.
{90042}{90099}Poèakaj!Ali lahko najprej nekaj reèem?
{90103}{90138}Deèko, utihni!
{90144}{90231}Povedal sem vam da je agentovo delo|varovanje ljudi.
{90240}{90285}To je moja družina.|Dovolj je!!
{90290}{90382}Delegati, èas je.|Družina ali formula.
{90389}{90425}Ne! Èakaj. Èakaj!
{90430}{90467}Ravno pred eno minuto...
{90470}{90505}... je v razburljivi razpravi....
{90507}{90573}... svet izglasoval,|da se žrtvuje družino...
{90579}{90694}... da bi zašèitili èloveštvo za |vedno pred maèjo nevarnostjo.
{90700}{90784}Za Pasje novice,|to je volk Blitzer.
{90790}{90836}Ubogi deèek.
{90843}{90893}Jaz potrebujem opremo, deèki.
{91062}{91109}-Poèakaj trenutek, deèek.|-Ne!
{91118}{91170}-Drži jo.|-Tega ne morejo narediti.
{91176}{91265}-Morali bi se držati mene!|-Kaj bi to spremenilo?
{91270}{91343}"Èlovekov najboljši prijatelj."|Zgodovina 101, se spominjaš?
{91349}{91423}Tukaj je lekcija dva.|Varjumo ljudi in delamo za njih.
{91428}{91506}Toleriramo njihova neumna otroèja nagovarjanja.|ZA KOGA?!!!
{91507}{91548}Potem gredo na faks. . .
{91554}{91646}. . .in te dajo k kakšni stari ženski,|ki še palice ne more metati!
{91680}{91730}Kaj se je to zgodilo tebi??
{91755}{91834}Ti kriviš mojo družino za tisto kar|je neki deèek storil tebi.
{91923}{92004}Glej, deèko. Oprošèam se èe|izpadlo tako. . .
{92010}{92069}. . .toda je konec. Izkljuèili so nas.
{92142}{92229}Ne bodi plašen, Scotty.|Vse bo OK.
{92235}{92272}Nisem prestrašen, mama.
{92278}{92339}Vse je v redu. Saj je èisto naravno.
{92344}{92417}-Torej bo OK.|-Mama, res, jaz sem OK.
{92421}{92477}Trudiš se biti pogumen.
{92481}{92512}-Dobro je.|-Mama--
{92517}{92559}Scotty, ne bodi prestrašen!
{92573}{92652}-Jaz sem tvoja skala!|-Prosim vas.
{92672}{92731}Kdo nas je ugrabil,|Uruguay or Chad?
{92736}{92795}Slišal sem kaj se je zgodilo.|Kako Lou?
{92800}{92883}-Povedal sem mu naj ne postane vdan.|-"Agent se koncentrira. . 
{92888}{92930}. . .samo nam misijo.
{92935}{93035}-Zato me ni moja družina imela rada."|-Vsi imamo limonasto zgodbo.
{93040}{93082}Tudi on ima svojo.
{93742}{93814}-Jaz morem iti.|-Pojdi preden gremo.
{94024}{94077}Prinesel si rezultate raziskav.
{94086}{94136}Neumen kuža.
{94351}{94405}Vzel je rezultate.
{94536}{94557}Lou.
{94565}{94604}Butch, ali si tam?
{94610}{94670}Lou je v težava v pristanišèu!
{94674}{94717}Dok 14. Pohiti!
{94721}{94900}Lou!
{95600}{95690}Pretentali so me.|Bili so vse povsod.
{95691}{95720}Ali so vzeli formulo?
{95724}{95797}Mislil sem, da bodo spustili družino, | èe jim bom dal formulo.
{96073}{96166}Koliko psov je potrebno|da spodrine èloveštvo?
{96171}{96229}Samo eden neumen kužek.
{96234}{96274}Kje je moja družina?!
{96278}{96311}Oh, živi so.
{96316}{96341}Za sedaj.
{96352}{96398}Toda to ni pomembno--
{96454}{96491}Toda to niso dirke!
{96517}{96556}Zasegel sem formulo. . .
{96561}{96615}. . .in v eni uri je bom pripravil. . .
{96620}{96638}. . .da bo mogoèe. . .
{96643}{96682}... unièiti ljudi...
{96811}{96915}Kako naj uživam v razburljivosti|èe voziš kot opica?!
{96926}{97038}Naredil bom tako da bo èloveštvo|zelo alergièno na vašo vrsto.
{97043}{97121}In ko bodo vsi tisti katere varujete|jezni na vas...
{97127}{97193}... boste pregnani in| pustili meni da jih vodim...
{97197}{97252}. . .maèke v veliko revolucijo. . .
{97256}{97299}... da osvojimo svet!
{97338}{97371}-Kaj bomo storili?|-"Mi"?
{97376}{97483}Za vedno si dal èloveštvo v propad.|Niè veè ne moremo storiti.
{97493}{97560}Ti se vedno prehitro vdaš, Butch.
{97601}{97664}-Kaj je to, to, kar mislim da je?|-Kaj, Butch?
{97669}{97727}Jup, to je maèji slednik 2000.
{97787}{97876}Te vreèe |že teèejo v hribe.
{97893}{97935}Tako jez mislim.
{97995}{98057}Hitreje. Mislil sem da si v sindikatu!
{98072}{98121}Imam bonus za deèka...
{98418}{98491}To je to.|Božièna jelka iz zapiskov.
{98580}{98639}Kaj pa sedaj nameravajo?
{98745}{98798}Z vsemi temi miši bi|lahko nahranili vojsko.
{98941}{99006}-Pozdravljeni, profesor Brody.|-Kdo pa si ti?
{99039}{99076}Oprostite ker ste èakali. . .
{99082}{99148}-. . .toda imel sem teste.|-kdo je to?
{99152}{99187}Kdo ste vi?
{99193}{99238}Kaj je to o mojem delu?
{99268}{99308}Ti si eden od tistih. . .
{99312}{99400}. . .velikih multinacijonalk,|združenj, profita-laènih. . .
{99404}{99465}. . .farmacevtskih družb|katere kradejo--
{99471}{99518}Farmacevtskih družb?
{99539}{99578}Nismo se razumeli.
{99585}{99625}Kaj je dogaja? Halo?
{99660}{99708}Ta vonj.|Maèjega porekla--
{99839}{99866}Kje si?
{99937}{99999}Pokaži se.|Ne moreš se skrivati za vedno.
{100067}{100120}Toda, nimam niè za skrivati.
{100293}{100338}Cool!
{100598}{100664}Naj jih nekdo utiša?!
{100709}{100784}Imam zelo pameten test za izpeljati.
{100797}{100866}Ali ste vi mutanti?|Bral sem ta strip--
{100870}{100912}"Bral sem strip."
{100917}{100971}Ti me delaš bolnega!
{101028}{101092}Pomiri se, draga. Pomiri se.
{101098}{101180}Eksperiment se je slabo zaèel.|Postala si modra!
{101240}{101281}Je bil že èas.
{101341}{101378}Moja prevzeta publika . .
{101384}{101493}. . .Kaj se hoèem igrati,|mladi Brody? Oprosti mi.
{101499}{101556}Steklenièko! Zeleno!
{101561}{101587}Tukaj, šef.
{101624}{101685}Oh, zdravo, Gos. Zlobni Serum.
{101690}{101728}-Kaj je v tem?|-Torej. . .
{101734}{101804}. . .lažni sneg mojega" šefa". . .
{101812}{101874}. . .je popoln za prenašanje . .
{101879}{101914}. . .vaše bolezni.
{101950}{102002}Ah, da. Thereby. . .
{102008}{102085}. . .prelomna vez med deèkom|in njegovim psom.
{102090}{102112}Ne,poèakaj.
{102141}{102170}Poredna. Poredna govoreèa maèka.
{102171}{102206}Ploha.
{102222}{102259}Spustite kletke!
{102487}{102515}Uspeh! Ti!
{102522}{102594}-Razporedite enote.|-Da, gospod.
{102686}{102769}A kar se vas tièe Brody. . .
{102774}{102811}. . .imam zelo. . .
{102818}{102863}. . .zelo poseben. . .
{102878}{102914}. . .darilo! Kaj?!
{102947}{102991}Rekel sem da kupi pravo pištolo!
{102998}{103117}-To sem jaz mislil.|-Kakšne koristi naj imam od tega?!
{103337}{103389}Ej! Jaz sem tako pameten.
{103421}{103484}To je èista zabava.
{103524}{103565}-Ostani tu.|-Zakaj?
{103570}{103606}Ker te sovražim.
{103636}{103712}Ne! Pomagaj! Pusti me ven!
{103739}{103775}Èez nekaj ur. . .
{103782}{103880}. . .vsak èlovek na svetu|bo alergièen na pse.
{103886}{103987}Toda v takem trenutku naèrt|zahteva brata v vojski.
{103993}{104030}In tu. . .
{104034}{104121}. . .se moja genialnost |resnièno izkazuje.
{104127}{104249}Za svojega tovariša sem izbral nekoga|ki se lahko privadi na vsak dom na svetu.
{104384}{104416}Miši!
{104438}{104475}Mamin sine!
{104479}{104549}Miši! Nepredvidljiv zavezniki.
{104631}{104669}Vsi se sprašujete:
{104674}{104756}"Kako lahko razširimo alergijo|po svetu?"
{104782}{104875}Odprite svetovno dominacijo letakov in|pokazal vam bom.
{104931}{105025}Pojdite v kanalizacijo in po mapah|v dodatek B. . .
{105029}{105105}. . .razširite se po svetu.|Polovica vas gre v hiše. . .
{105110}{105171}. . .okužite vsakega èloveka,|medtem ko ostali--
{105187}{105216}Obrnite list.
{105243}{105304}--se pritihotapijo |na letala in èolne. . .
{105308}{105382}. . .okužimo svet.Z pasjem izginotjem. . .
{105388}{105499}. . .maèke bodo porazile ljudi|in vam bo dana nagrada:
{105503}{105575} 8 kil  Monterey Jack sira. . .
{105581}{105655}. . .in celo Avstralijo!
{105708}{105746}-Avstralijo!|-Jeah!
{105751}{105790}Odprite pokrov kanala!
{105918}{105963}Dobro, tukaj je naèrt.
{106150}{106204}Razbežite se po celem svetu!
{106209}{106255}Pojdite ven in okužite vse!
{106266}{106311}Bodite vse kar ste lahko!
{106317}{106386}Moj naèrt je prišel  v konèno fazo!
{106396}{106551}Niè se nimate za bati, razen mišolovke . .|.. in mene.
{106554}{106584}Pojedel je Gary-a!
{106594}{106624}Beži!
{106661}{106694}Kaj je bilo to?
{106871}{106908}Konec je, Tinkles!
{106912}{106949}Psi. Kje so?
{107001}{107064}Lou, loputa. Zapri loputo.
{107107}{107142}Ob nepravem èasu!
{107171}{107218}Predajte se.Konec je!
{107252}{107275}Gremo!
{107287}{107328}Jaz morem ulovit letalo.
{107698}{107778}Ivy,pojdi poiskati Peeka in Sama.|Jaz morem poiskati Lou.
{107938}{107962}Dober deèko.
{108022}{108060}Ej! Ustavi se!
{108067}{108111}Ustavi se. Morem te unièit.
{108116}{108155}Dobil te bom.
{108210}{108260}Kako je nas dobil?
{108265}{108342}-Pohiti, moreva iti.|-Ali tudi ti govoriš?
{108436}{108477}Popraskal bom za tebe!
{108538}{108590}Stisnil te bom kot klopa!
{108702}{108728}Pridi, ljubica!
{108758}{108826}Pridi sem.|Zate imam mleèno kost.
{108904}{108932}Sedaj te imam.
{109008}{109099}-Daj me dol, kosmata žoga!|-Jaz hoèem samo objem!
{109162}{109230}Prihajam, Butch!
{109334}{109382}Tukaj, muci, muci, muci.
{109387}{109452}Prepozen si, kužek.
{109500}{109526}Jaz sem kralj svet!
{109530}{109554}Ulovi ga, Lou!
{109566}{109630}Vdam se. Prosim ne me poškodovati.
{109642}{109704}Spravi se stran,|Tinkles!
{109980}{110034}Torej,kje sem ostal? Oh, da.
{110178}{110221}Sedaj pa zadnji udarec.
{110582}{110621}Pasi so glavni!
{110666}{110707}To je samo manjši neuspeh.
{110730}{110783}Ti si konèal, Fluffy!
{110842}{110880}Butch! Uspeli smo!
{111257}{111324}-Gremo, Scotty!|-Gremo! Hitro!
{111474}{111500}Gremo!
{111761}{111825}Poèakajte. Kje je Lou?!
{112976}{113022}Deèko, uspeli smo.
{113025}{113101}Rešili smo jih, kot si rekel.|Imel si prav.
{113106}{113154}In imel si prav o meni.
{113160}{113181}Deèko?
{113274}{113310}Oh, ne.
{113967}{114006}Pridi, Lou, zbudi se.
{114058}{114107}Ti nisi zguba, Lou.
{114145}{114197}Si moj najboljši prijatelj.
{114250}{114277}Zbudi se.
{114370}{114430}Tudi ti si moj najboljši prijatelj.
{114638}{114701}Mama, oèe, živ je!
{114711}{114786}Mama, oèe, živ je!
{114792}{114824}Pridi hitro!
{114854}{114881}Prišel je nazaj!
{114886}{114959}-Imate pravico -| -Imate pravico. . .
{114965}{115050}-. . .da ostanete tiho.|-Vse kar reèete  bomo lahko uporabili. . . .
{115056}{115099}Oh, moj bog!
{115103}{115155}In pravica do pasjega odvetnika.
{115306}{115341}Dobi ga, Lou! Pohiti!
{115346}{115389}Nihèe! Postajaš dober.
{115427}{115468}Daj roke naprej.
{115551}{115582}Dobro, Oèe!
{115588}{115657}-Lou, pojdi jo iskati.|-To je trojna.
{115662}{115694}Hej, otrok.
{115702}{115753}Ali gre vse dobro v štabu?
{115758}{115828}Jejo mi iz taèk.|Kako je pri tebi?
{115832}{115943}-Dobro. Ali se hoèeš igrati z žogo?|-Ne, morem iti nazaj v službo.
{115990}{116041}Prinesi jo sem. Najdi žogo.
{116141}{116218}Pridi! Pojdi jo iskati! Pridi!
{116223}{116268}Ima jo! Ima jo!
{116274}{116361}Prinesi to žogo!|Prinesi to žogo nazaj!
{116384}{116454}Bil bi odlièen agent.
{116589}{116711}Prav imate,Gos. Tinkles.|Bil si zelo poreden maèek.
{116717}{116805}Sedaj pa te samo nauèim |kako se obnaša.
{116843}{116958}No sedaj pa boš  mogel živeti z  mano|in mojo sestro!
{116985}{117029}Gos. Tinkles!
{117155}{117234}Poglej kaj smo naredili zate!
{117426}{117509}-Nisem te mogel pojesti z žlico!|-Jaz tega ne morem prenesti!
{117515}{117934}Prevedeno by Logo Masters.
{117935}{117971}To ni res :))).