{438}{476}Finally...
{477}{556}the warring nations of earth had|forgotten their differences...
{557}{627}and banded together|to save our planet.
{654}{756}The United Global Space Force|was searching the galaxy...
{757}{832}for worlds rich with drinkable|water and breathable air.
{849}{928}The hypergate was our best hope|to colonize space...
{929}{968}our best hope for survival.
{969}{1017}But as we prepared|to launch ourselves...
{1018}{1053}into the black of space...
{1073}{1180}terrorists, calling themselves|"The Global Sedition..."
{1181}{1229}were preparing to strike.
{1254}{1329}Subtitles downloaded from Podnapisi.NET
{1363}{1446}Grissom base, this is Cargo 7|requesting landing clearance.
{1446}{1493}Roger, transport.|This is Grissom gate control.
{1494}{1521}Please download security codes.
{1522}{1551}Downloading.
{1552}{1622}Transport, I've got two blips|inside your radar signature.
{1622}{1653}They're hiding in your shadow.
{1654}{1686}I don't see anything.
{1808}{1875}This is gate control.|Battle stations.
{1954}{1985}Battle stations.
{1986}{2052}Two Sedition fighters|are attacking the hypergate.
{2053}{2086}Battle stations.
{2086}{2139}Gate control, this is Eagle One.|I'm locked and loaded.
{2140}{2181}Ready to fly.
{2182}{2237}Roger, Eagle One.|You're clear to launch.
{2357}{2395}Jeb, where are you, buddy?
{2433}{2497}This cold war just got hot.
{2498}{2532}They're Sedition raiders.
{2533}{2591}It's another|mutant suicide squad.
{2626}{2678}Here we go. Man-to-man.|Split them up.
{2679}{2773}Last one to kill a bad guy|buys the beer.
{2850}{2901}I'm gonna go through the gate,|get in front of him.
{2902}{2964}That's not standard procedure,|Don.
{3049}{3085}I'm gettin' some heat.
{3311}{3352}You gen-techs are ugly up close.
{3353}{3386}Target lock.
{3387}{3415}Show time.
{3606}{3650}Bogey One dispatched.
{3670}{3749}Don, he's right on my tail.
{3750}{3782}Damn! Can't shake him.
{3918}{3949}I've been hit!
{3950}{3979}Weapons are off-line.
{3999}{4041}I'm gonna jettison|the main drive core.
{4042}{4072}There you are.
{4246}{4293}Am I good or what?
{4294}{4358}Warning. Failure|in redundant drive systems.
{4359}{4415}Gate control,|this is Ranger One.
{4416}{4458}Engines will not respond.
{4481}{4566}Don, I'm falling|towards the hypergate.
{4567}{4619}Breaking thrusters won't fire!
{4630}{4690}Impact in 30 seconds.
{4690}{4722}Ranger One, this is base.
{4723}{4776}Rescue craft|have been dispatched.
{4821}{4906}Grissom, those pods will never|reach him in time.
{4907}{4935}I'm going in.
{4936}{5003}Major West, you are not|authorized to jeopardize--
{5004}{5043}Never liked that station anyway.
{5044}{5122}Warning. Proximity alert.
{5219}{5246}Hang on, Jeb. I'm coming in.
{5247}{5311}Abort. Abort!
{5312}{5385}I'll give you a little kiss.|Don't take this the wrong way.
{5386}{5441}Impact in five seconds.
{5898}{5946}Does this mean|we're going steady?
{5946}{6018}You're not getting out|of buying those beers that easy.
{6346}{6409}With intrepid pioneering spirit,|the Robinson family...
{6410}{6479}will journey to the distant|world of Alpha Prime.
{6480}{6553}What kind of future can|our children look forward to?
{6554}{6605}A future in paradise.
{6606}{6638}The Jupiter mission...
{6638}{6725}made possible by the Army and|Silicon Graphics Corporation.
{6726}{6830}S.G.I. Saving the future|for our children.
{6831}{6880}Give me a break.
{6881}{6935}Holo-call|from Houston middle school.
{6936}{6965}Hello?
{6966}{7010}Hello, Principal Cartwright.
{7010}{7061}What has he done this time?
{7062}{7168}He hacked our main power grid|to run his experiment.
{7188}{7227}The school was in chaos.
{7242}{7277}Yeah, right.
{7278}{7326}We didn't even have lights.
{7417}{7505}This is no laughing matter,|Professor Robinson.
{7506}{7590}Will is terribly gifted.
{7591}{7658}The changing shape of education.
{7658}{7730}His little time machines,|though pure fancy...
{7730}{7802}are the products|of a truly brilliant mind.
{7845}{7889}No more monkey business.
{7890}{7932}I mean it.
{7933}{7995}The boy is starved|for attention.
{7996}{8076}I know your life is anything|but normal right now...
{8077}{8120}but wasn't there some way...
{8121}{8202}his father could have|attended the science fair?
{8203}{8250}As you are aware...
{8251}{8322}Alpha Prime is the only other|habitable planet...
{8323}{8416}yet detected|by deep space recon.
{8439}{8524}My crew will sleep away|our 10-year journey there...
{8525}{8569}in suspended animation.
{8593}{8670}Once we have rendezvoused with|the research colony on Alpha...
{8671}{8736}I will supervise|construction of a hypergate.
{8737}{8812}By then,|technicians here on Earth...
{8813}{8893}will have completed|the companion hypergate...
{8894}{8945}in our planet's orbit.
{8983}{9026}Once both gates are complete...
{9051}{9162}ships will be able to pass|instantaneously between them.
{9163}{9254}Immediate colonization|of Alpha Prime will be possible.
{9255}{9330}Can't you just use|the Jupiter's hyper-engine...
{9331}{9377}to zap straight to Alpha Prime?
{9394}{9462}Hyperspace exists|beneath normal space.
{9463}{9546}If you try to enter hyperspace|without a gate...
{9568}{9610}your exit factor is random.
{9611}{9654}There's no telling|where you'd come out.
{9674}{9746}Ninety-eight percent of|the galaxy is still uncharted.
{9747}{9815}There's a lot of space|to get lost in.
{9867}{9929}How is Captain Daniels|recovering from the flu?
{9930}{9974}Will he pilot the mission?
{9975}{10026}Ladies and gentlemen.
{10027}{10127}You came to get your first look|at the Jupiter 1.
{10128}{10169}Don't you think|you've waited long enough?
{10194}{10238}Let's move into the launch dome.
{10238}{10272}One more question, Professor.
{10273}{10338}Now that the mission's|been pushed up...
{10339}{10410}how do your children feel|about leaving the earth behind?
{10411}{10473}They couldn't be more excited.
{10500}{10551}This mission sucks!
{10552}{10610}I don't wanna leave early.|I don't wanna go at all.
{10611}{10644}We will discuss this at dinner.
{10673}{10753}For the last three years, I've|missed everything training...
{10754}{10821}so I can spend the next 10 years|missing everything else.
{10850}{10898}I'm not staying home for dinner.
{10898}{10935}I'm seeing my friends.
{10936}{10979}Penny.
{10980}{11070}I'm going out to say good-bye|to my entire life.
{11094}{11161}Penny, I need you here tonight.|Wait a minute.
{11334}{11429}On this eve, before she's torn|from everything she knows--
{11430}{11477}kidnapped...
{11478}{11553}hurled into deep space|against her will--
{11554}{11631}what thoughts fill the mind|of the daring space captive?
{11632}{11674}Are there boys on Alpha Prime?
{11675}{11718}What will I wear?
{11792}{11881}What will it be like to jettison|your body into deep space?
{11915}{12003}First...|you'll try holding your breath.
{12004}{12084}But your blood's|already begun to boil.
{12085}{12200}Then your skin inflates|like a balloon.
{12201}{12262}Then...pop.
{12263}{12309}Do they have a name|for what's wrong with you?
{12400}{12441}Dad says don't bring them.
{12442}{12499}Like anything I do|matters to him.
{12500}{12554}Don't sweat it, kid.
{12555}{12650}I got apology videos|for two birthdays.
{12651}{12708}He forgot last year completely.
{12734}{12799}This mission's the only thing|he cares about anymore.
{12951}{12998}So that's a no to family dinner?
{12998}{13042}Let's see.
{13043}{13091}Do I spend my last night|on Earth...
{13092}{13177}watching Mom and Dad pretend|not to be fighting again...
{13178}{13249}or blow 10 years worth|of allowance at the mall?
{13286}{13322}You do the math.
{13323}{13354}Mom's gonna go thermal.
{13378}{13424}What's she gonna do,|ground me?
{13456}{13526}I'm nervous about jamming in|a new pilot the last second.
{13527}{13577}The Global Sedition|is getting brave.
{13578}{13629}First the hypergate,|then Daniels.
{13630}{13686}Next time, they may attack|the launch dome.
{13686}{13722}We can't afford to wait.
{13723}{13820}Will's science fair. Reminder.|Apology video for Will.
{13821}{13849}He'll understand.
{13850}{13886}Ben, listen.
{13887}{13966}My family is on this mission.
{13966}{14024}I need a pilot who's|more than just spit and polish.
{14025}{14068}I've got your man.
{14069}{14113}He just doesn't know it yet.
{14242}{14269}At ease, Major.
{14270}{14316}Why was I pulled|from active duty?
{14317}{14352}Those gen-techs|may attack again.
{14376}{14404}I need to be up there.
{14405}{14446}Do you know Professor Robinson?
{14447}{14533}By reputation. Your father's|battle strategies...
{14534}{14583}were required reading|at the academy.
{14602}{14662}What can you tell me|about the Jupiter mission?
{14698}{14740}The Jupiter|is an oversized robot.
{14760}{14794}Everything's automatic.
{14834}{14869}Any monkey in a flight suit...
{14870}{14925}can pilot that ship|out of the solar system...
{14926}{14977}and set her down on Alpha Prime.
{14978}{15048}It's a baby-sitting job, sir.
{15049}{15081}No offense.
{15082}{15183}Major, are you aware Earth's|resources are severely limited?
{15184}{15215}Every schoolchild knows...
{15216}{15286}that our recycling technologies|will cure the environment.
{15314}{15359}Sending a family|across the galaxy...
{15360}{15445}is a stunt to sell computers|to people of all ages.
{15446}{15485}Every schoolchild was lied to.
{15486}{15552}Recycling technologies|came too late.
{15553}{15625}All fossil fuels|are virtually exhausted.
{15626}{15689}The ozone layer is down to 40 % .
{15690}{15836}In two decades, the earth will|be unable to support human life.
{15837}{15915}The new Global Sedition knows|the truth as well as we do.
{15916}{15963}They're building|their own hypergate.
{15964}{16035}They hope to colonize|Alpha Prime first.
{16036}{16080}If they're successful...
{16081}{16138}western demons like you and I,|Major West...
{16139}{16190}will be left on Earth to die.
{16191}{16249}Captain Daniels doesn't have|the flu, does he?
{16250}{16335}Captain Daniels was murdered|in his apartment last night.
{16336}{16387}The flu story is a cover.
{16388}{16441}I flew with Mike.
{16456}{16529}We should blast their bases!|A decisive strike now!
{16530}{16565}My squadron is alert status--
{16566}{16624}Your rescue stunt was foolhardy!
{16625}{16666}I had a friend in trouble.
{16667}{16726}So you endangered|a $10-billion spacecraft...
{16727}{16789}disobeyed a direct order|because of a friend?
{16826}{16854}I did...
{16882}{16910}sir.
{16969}{16997}He'll do.
{17110}{17149}Congratulations.
{17150}{17209}You're the new pilot|of the Jupiter mission.
{17266}{17343}Where's my money?
{17462}{17519}The Sedition hired me|to provide access...
{17520}{17581}to Daniels' apartment|and no more.
{17582}{17633}My work is done.
{17659}{17708}They found a replacement pilot.
{17709}{17762}Our attack|on the hypergate failed.
{17763}{17810}How tragic for you.
{17841}{17937}We require a more direct|intervention on your part.
{17938}{17974}I see.
{18035}{18083}It will cost you.
{18119}{18214}I'm afraid that my price|has just become...
{18215}{18255}astronomical.
{18291}{18324}Holograph off.
{18550}{18578}Come in.
{18700}{18789}Control hasn't received|results of the preflight exams.
{18790}{18858}The Robinsons|have checked out 100 % .
{18935}{19008}They're fit as a fiddle|and ready to fly.
{19009}{19037}Wish them luck...
{19062}{19097}for me.
{19243}{19328}Mission protocols are simple.|Robinson is in command...
{19329}{19365}unless you encounter|a military emergency.
{19366}{19419}In that case, Major West,|you are in charge.
{19420}{19490}I'm a fighter pilot.|There must be better candidates.
{19490}{19550}Hell, even my own family|can't stand me.
{19551}{19586}Shut up.
{19653}{19719}Jeb Walker.|He's an excellent flyer.
{19720}{19753}He's perfect for this mission.
{19754}{19789}Welcome aboard, Major.
{20226}{20278}Looks like somebody sprung|for the full-extras package...
{20279}{20311}on this beauty.
{20312}{20413}If you have to be a baby-sitter,|it's not such a bad nursery.
{20414}{20456}Wouldn't you agree?
{20492}{20520}I don't get it.
{20521}{20595}I can't get the cryo-sleep|systems up over 96 % .
{20596}{20647}Dr. Smith approved the specs.
{20648}{20739}Dr. Smith is the base physician.|I am responsible in flight.
{20740}{20798}These tubes will be perfect,|or the ship will not launch.
{20798}{20825}Is that clear?
{20826}{20890}Absolutely, Doctor.
{20891}{20988}Judy, I want to introduce you|to Major West.
{20989}{21030}He'll be taking Mike's place.
{21100}{21156}He's heavier than Mike.|We'll have to recalibrate.
{21173}{21239}I'd be happy to discuss|my dimensions, Doctor...
{21240}{21276}say, over dinner?
{21300}{21348}West.|I've read about you.
{21349}{21392}You're a war hero, aren't you?
{21393}{21452}Well, yes, actually.
{21476}{21560}Who was it who said,|"Those who can't think, fight"?
{21584}{21642}I think that it was me.
{21642}{21686}It was nice to have met you.
{21798}{21876}That's one cold fish|I'd love to thaw.
{21904}{21979}I'm not gonna make it over|for dinner tonight, Dad.
{22225}{22262}It's gonna be a long flight.
{22315}{22365}Maureen, pick up the phone,|honey.
{22366}{22405}I know you're there.|Are you still packing?
{22406}{22441}I'm just leaving.|Go to bed.
{22742}{22770}Sweetie?
{22962}{23006}He won first prize again.
{23007}{23064}Is this the new model|he's been working on?
{23185}{23236}Crazy idea he's got about a...
{23262}{23309}time machine?
{23365}{23425}Pretty sharp stuff for a midget.
{23461}{23512}Sorry about dinner.|That new pilot--
{23513}{23548}John, the family needs you here.
{23549}{23614}This whole thing|is about family.
{23632}{23680}My only condition|for accepting this mission...
{23681}{23754}was that we could bring|the children with us...
{23755}{23785}not leave them behind...
{23786}{23850}so future generations|would have a new home.
{23851}{23922}You're off saving humanity,|so what does it matter...
{23922}{23976}that Will|has to blackout his school...
{23977}{24028}to get his father's attention...
{24029}{24127}Penny's been dragged home|by security 3 nights in a row...
{24128}{24180}Judy's become a ghost,|like her father?
{24181}{24230}I have to compensate|for the new launch time.
{24231}{24275}What do you think I'm doing?
{24276}{24309}Revising life-science protocols.
{24310}{24357}I'm also dealing|with two kids...
{24358}{24420}who are leaving|an entire planet behind.
{24421}{24511}Sorry, but there's no manuals|on how to deal with this.
{24594}{24643}Maybe it doesn't do any good...
{24723}{24811}saving a world of families|if we can't save our own.
{24888}{24923}Is that it, Professor?
{25039}{25066}John.
{25067}{25119}I know, baby.|I'm scared, too.
{25830}{25874}Med supplies for the Jupiter 2?
{25875}{25909}That's what it looks like.
{25938}{25973}They're not taking any chances.
{27150}{27242}Forgive me if I forego the kiss,|my sleeping behemoth...
{27243}{27309}but the time has come to awake.
{27310}{27354}Robot is on-line.
{27355}{27405}Reviewing primary directives.
{27406}{27492}One--|preserve the Robinson family.
{27493}{27545}Two--|maintain the ship's systems.
{27546}{27645}Spare me the chatter,|my steely centurion.
{27646}{27757}Sadly, I fear I have far more|dire deeds in store for you.
{27782}{27829}Robot is on-line.
{27830}{27876}Reviewing primary directives.
{27877}{27961}Sixteen hours into mission,|destroy Robinson family.
{27962}{28022}Destroy all systems.
{28023}{28082}That's more like it.
{28082}{28138}Farewell,|my platinum-plated pal.
{28204}{28257}Give my regards to oblivion.
{28460}{28570}Apparently you have completed|your mission on schedule.
{28571}{28663}I do so admire a spot|of timely terrorism.
{28664}{28735}I thought I told you|never to call me here.
{28736}{28806}The transmission signal|will be traced.
{28807}{28903}I just wanted to express|my most sincere gratitude...
{28904}{28993}for your unflagging loyalty.
{28994}{29051}Good work, good doctor...
{29052}{29096}and good-bye.
{29478}{29569}Jupiter 1 launch|in three minutes.
{29570}{29608}Mom, just--
{29609}{29636}Shoot.
{29637}{29664}Mom, I'm fine.
{29665}{29700}That's supposed to be there.
{29724}{29779}This is almost acceptable.
{29803}{29852}-Mom, don't.|-What?
{29853}{29913}Vogue says this will be|the style in 10 years.
{29914}{29951}Can we cut back on her oxygen...
{29952}{30017}so she's not so annoying|when she wakes up?
{30018}{30052}Does he have to wake up at all?
{30053}{30121}That's it. I'm gonna turn|this spaceship around.
{30122}{30205}Satellite defense net locked|and a-ok.
{30810}{30885}-Everything's gonna be fine.|-30 seconds. Mark.
{30886}{30946}-Hey, there, buddy.|-Com-links encoded and secure.
{30946}{30997}-Good night, guys.|-Good night.
{30998}{31037}Here we go.
{31038}{31100}Artificial gravity at 100 % .
{31101}{31152}You get a "C"|in paternal expression...
{31153}{31209}but an "A" for effort.
{31210}{31266}-I'm doing the best I can.|-Come here.
{31374}{31422}You always get an "A" in this.
{31422}{31481}Main drive systems on-line.
{31482}{31526}Sweet dreams.
{31527}{31558}See you there.
{31591}{31685}You are at "T" minus one minute|and counting, Major West.
{31899}{31940}Houston, the bird is hot.
{32012}{32041}She's all yours.
{32077}{32143}I'll try to give you|a smooth ride.
{32285}{32341}Mission control,|this is Dr. Robinson.
{32342}{32376}We are in the green.
{32377}{32461}Roger, Doctor. You are go|to initiate cryo-stasis.
{32546}{32577}One question.
{32613}{32677}Is there room|in these tubes for two?
{32705}{32769}There's barely enough|for you and your ego.
{32809}{32848}Don't sweat it, doc.
{32849}{32896}I do this all the time.
{32897}{32937}Just drive carefully.
{32990}{33061}You are at "T" minus 40 seconds|and counting.
{33062}{33090}Ready.
{33323}{33408}You are at "T" minus|30 seconds and counting.
{33728}{33798}You are at "T" minus|20 seconds and counting.
{33799}{33842}Control, this is Jupiter 1.
{33843}{33886}The Robinsons are all tucked in.
{33887}{33917}We are ready to fly.
{33918}{34014}Major West, your escape vector|is clear of all traffic.
{34015}{34073}Op is go on your command.
{34074}{34114}Roger, Houston.
{34115}{34176}And the monkey flips the switch.
{34986}{35057}Jupiter 1 boosters disengaged.
{35242}{35286}This is Jupiter 2.
{35286}{35369}Diverting all spacecraft control|to the main computer.
{35420}{35464}Eight years of flight training.
{35526}{35597}Navigational holographics|on-line.
{35598}{35637}Fifty combat missions.
{35693}{35765}Course confirmed for slingshot|exit of the solar system.
{35826}{35922}So I can take the family camper|on an interstellar picnic.
{35992}{36052}Ten years is a lifetime.
{36088}{36126}Sleep well, old friend.
{36172}{36237}I never liked|these freezing tubes.
{36320}{36352}Bad dreams.
{36548}{36635}Navigational interface|confirmed.
{36636}{36708}Cryo-sleep systems are 100 % .
{37673}{37701}Shit!
{37826}{37878}Robot is on-line.
{37879}{37962}Sixteen hours into mission,|destroy Robinson family.
{37962}{38011}Destroy all systems.
{38012}{38075}Disable program !
{38076}{38147}Sixteen hours into mission,|destroy Robinson family.
{38148}{38194}Destroy all systems.
{38209}{38265}Robot is on-line.
{38266}{38294}Destroy.
{38404}{38478}Destroy all operating systems.
{38479}{38532}Destroy Jupiter 2.
{38630}{38702}Destroy all operating systems.
{38703}{38751}Destroy Jupiter 2.
{38752}{38822}Destroy cryo-sleep systems.
{38939}{38974}Destroy.
{39170}{39216}Destroy navigational systems.
{39279}{39339}Come on!|Wake up, damn you!
{39395}{39474}I can't stop this infernal|contraption on my own.
{39590}{39688}Emergency cryo-stasis|desequencing in process.
{39689}{39753}Destroy all systems.
{39754}{39789}Destroy Robinson family.
{39790}{39839}Maureen, the children!
{39840}{39868}Destroy.
{39894}{39925}Run!
{39944}{40003}-Destroy.|-Deactivate safety.
{40115}{40178}That was a mistake.
{40402}{40442}Dad!
{40524}{40560}Mom, let's go!
{40578}{40665}-Will, stop!|-Destroy.
{41095}{41134}Destroy Jupiter 2.
{41222}{41282}Destroy Robinson family.
{41614}{41659}Look away, baby.
{41693}{41755}Robot, disable pulse blaster.
{41756}{41783}Command accepted.
{41784}{41835}Cancel attack sequence|and stand by.
{41913}{41982}If the family won't come|to the science fair...
{41983}{42045}bring the science fair|to the family.
{42089}{42117}Showoff.
{42142}{42176}Robot.
{42177}{42227}On-line. Standing by.
{42228}{42295}Return to docking bay|and power down.
{42296}{42339}Major, you all right?
{42340}{42410}Next picnic, no robots.
{42443}{42475}Where's Judy?
{42564}{42634}Stabilize the operating systems.
{42634}{42665}Fire control.
{42666}{42725}Attempting|containment protocols.
{42758}{42799}I want to go home now.
{42815}{42872}Navigation's down.|System shorts everywhere.
{42873}{42936}Damn.|Communications are out.
{42937}{42987}Link up the secondary system.
{42988}{43051}-Shunting power from reserve.|-Come on.
{43052}{43080}Try it now.
{43081}{43118}Navigational boards are lit.
{43144}{43189}Can we reroute?
{43190}{43239}I'm locked out of the helm.
{43240}{43285}Nothing in computer control.
{43286}{43321}Main com to manual.
{43322}{43374}See if she'll respond.
{43375}{43453}The main subroutine won't open.|I'm gonna try remote ops.
{43518}{43545}Smith!
{43546}{43604}Get back!|Get away from me!
{43605}{43675}What the hell|are you doing here?
{43676}{43758}Major West,|thank God it's you.
{43759}{43821}I was in here|to do some last minute checks...
{43822}{43849}and somebody hit me from behind.
{43850}{43894}That's Sedition technology.
{43918}{43950}You're the damn spy.
{43951}{43982}You did this.
{44038}{44073}What are you doing?
{44074}{44098}Throwing out the trash!
{44099}{44135}I need help!
{44156}{44219}I can't get Judy out!|She's dying!
{44323}{44374}Touch me,|and the girl dies!
{44375}{44425}I don't deal with dead men.
{44426}{44465}Kill me, kill the girl.
{44502}{44545}How much is your revenge worth?
{44546}{44594}I can save her life...
{44595}{44681}only if you give me your word|as an officer you'll spare mine.
{44743}{44826}-Help her.|-I've got helm control.
{45058}{45109}We're way off course.
{45183}{45241}We're caught in the sun's|gravitational pull.
{45242}{45284}Is that what that big ball is?
{45384}{45466}We've got four minutes before|the outer hull begins to melt.
{45467}{45539}I need you to check|on the thruster alignments.
{45540}{45585}Professor!
{45586}{45631}I'll try for the Mercury mines.
{45666}{45716}I'll need Dr. Robinson's|portable gurney.
{45717}{45751}You'll find it below.
{45752}{45801}Smith, come on!
{45870}{45926}You tried to kill my family.
{45927}{45957}We trusted you.
{45958}{46020}It's the world behind the world,|Professor Robinson.
{46021}{46111}Lie once, cheat twice,|and everything becomes clear.
{46112}{46224}Do not mistake my deception|for a character flaw.
{46225}{46259}It is a philosophical choice...
{46260}{46330}that I've found|in a study of the universe.
{46331}{46365}It is a way of life.
{46366}{46402}You're a monster.
{46403}{46465}Perhaps,|but I'm also the only one...
{46466}{46513}that can save Judy's life.
{46550}{46621}Penny, precious, I want you to|short the power on my command.
{46622}{46666}Does he have to call me|precious?
{46722}{46755}Penny, precious.
{46788}{46824}Now!
{46950}{46996}She's not breathing.
{46997}{47047}Sick bay, move!
{47048}{47080}The sun won't let us go.
{47081}{47126}Heat shield breach,|60 seconds.
{47127}{47154}I need options, Professor.
{47155}{47205}We have to divert all power|to the engines.
{47222}{47270}I'm rerouting life sciences.
{47271}{47324}Rerouting life support.
{47325}{47373}Engines at 80 % .
{47416}{47485}There's no cardiopulmonary|or respiratory functions.
{47713}{47746}Clear.
{47779}{47821}Again. Clear.
{47993}{48024}Alert.
{48025}{48054}Medical.
{48088}{48116}Rerouting error.
{48117}{48155}Systems are crashing.
{48244}{48294}We're losing her. Do something.
{48552}{48581}Come on, child.
{48628}{48682}Put a little heart into it.
{48710}{48744}The other life I save...
{48772}{48821}will be my own.
{48849}{48925}Wake up, baby, please.
{48977}{49037}That's all the power we've got.
{49038}{49084}I'm putting the pedal|to the metal. Here goes.
{49453}{49536}She can't break free.|She doesn't have enough thrust.
{49537}{49606}There's got to be a way|to get through this.
{49632}{49660}That's it.
{49773}{49800}It's working!
{49801}{49842}What is?
{49843}{49911}If we can't go around the sun,|we go straight through it...
{49912}{49941}using your hyperdrive.
{49942}{49999}Engage the hyperdrive|without a gate?
{50000}{50057}We could be thrown|anywhere in the galaxy.
{50058}{50086}Anywhere but here.
{50229}{50282}On my mark.
{50395}{50464}Three, two, one, initiate.
{51038}{51096}Hyperdrive at 100 % .
{51128}{51201}Major, you have the com.
{51234}{51262}Dad?
{51263}{51293}Dad!
{51343}{51391}Let's see what this baby can do.
{52232}{52290}Maureen, everyone?
{52354}{52388}-Where is Judy?|-She's OK.
{52389}{52459}She is, thanks to me.
{52484}{52512}Here I am.
{52535}{52580}Either I should cut down|on the liquids...
{52581}{52646}or I should sew in a new flap|because it was really hell...
{52647}{52683}getting out of that thing.
{52684}{52712}You're...
{52713}{52777}Vitals are normal. Pulse|and respiration seem to be.
{52778}{52825}-Are you OK?|-I'm fine, really.
{52826}{52854}Come here.
{52882}{52972}Will every little problem be an|excuse for familial sentiment?
{53072}{53100}How much, Smith?
{53132}{53229}What was the price tag|that you put on our future?
{53604}{53671}You can't do it, can you, John?
{53672}{53774}You can't kill the man|without becoming the monster.
{54001}{54031}Coward.
{54230}{54293}What's happened, John?|Where are we?
{54454}{54525}I bypassed|most of the damaged systems.
{54526}{54557}We'll have to repair the rest|manually.
{54615}{54650}You had me worried, doc.
{54651}{54696}Nice to see you thawed.
{54697}{54769}You have a puzzling definition|of a smooth ride.
{54770}{54869}Computer,|map our current position.
{54903}{54989}Searching|for recognizable constellations.
{55075}{55165}This database has star maps|of all the known galaxy.
{55166}{55229}I don't recognize|a single system.
{55291}{55332}We're lost....
{55360}{55395}aren't we?
{55783}{55818}Easy, doc. God.
{55818}{55846}Please.
{55847}{55923}The cryosuit absorbed|most of the electrical charge.
{55924}{55987}You're lucky|this wasn't your hide.
{55988}{56081}Doctor, is that concern|I detect in your voice?
{56133}{56187}Great bedside manner.
{56250}{56290}What's that?
{56291}{56332}A battle scar?
{56361}{56389}Sort of.
{56413}{56469}It was a tattoo.
{56470}{56569}An ex-girlfriend's name,|but I had it removed.
{56570}{56611}Wouldn't it be easier|to use a magic marker?
{56654}{56710}Yeah, well, that's me.
{56710}{56769}A girl in every port.
{56770}{56810}So, Major, no family?
{56811}{56882}Nothing to tie you down,|no one to miss?
{56883}{56962}I've never been|the fit-in and play-nice type.
{57022}{57059}You think that's romantic?
{57126}{57154}I don't.
{57185}{57244}But what about you, doc?
{57245}{57311}Is there some lucky little nerd|you left behind?
{57342}{57397}I spent three years working|on this mission.
{57398}{57452}We're trying to save the planet.
{57453}{57505}I haven't had time for fun.
{57506}{57582}If there's no time for fun...
{57583}{57640}then what are we saving|the planet for?
{57919}{57948}Here.
{57949}{57978}Thanks.
{57979}{58016}I hate being little.
{58174}{58224}I think it broke.
{58281}{58316}I'll try and fix it.
{58317}{58377}Why aren't you up on deck|with Mom and Dad?
{58378}{58413}Have you met our parents?
{58414}{58443}Good point.
{58491}{58529}Popcorn, orchids...
{58530}{58605}waves, Billy...
{58606}{58644}kissing.
{58691}{58720}Chocolate.
{58748}{58785}It's a list...
{58836}{58875}of everything we left behind.
{58996}{59030}Never love anything, kiddo...
{59064}{59114}'cause you just end up|losing it.
{59360}{59418}Smith could still hurt us.
{59463}{59517}Maybe I shouldn't let him live.
{59665}{59692}But...
{59693}{59752}How can we bring|civilization to the stars...
{59753}{59812}if we can't remain civilized?|Right, Professor?
{59813}{59898}Have you noticed that you|take the opposite position...
{59899}{59945}to whatever I say?
{59946}{59980}Of course I do.
{59981}{60024}We're married.
{60081}{60108}Alert.
{60109}{60180}Spatial anomaly in progress.
{60181}{60231}What the hell?
{60421}{60502}I must be dreaming.|That looks like a ship.
{60502}{60584}It appears to be some sort|of hole in space.
{60585}{60635}Where does it lead?
{60636}{60680}A reasonable question.
{60776}{60823}Major, wait.
{60824}{60858}I'll wait later.
{61021}{61054}Pull back.
{61054}{61093}Let there be light.
{61784}{61812}Proteus?
{61850}{61897}She's one of ours, all right.
{61981}{62010}All right.
{62048}{62096}I've never seen a ship|like this.
{62180}{62246}No response to hails.
{62247}{62334}Scanning all military|and civilian frequencies.
{62335}{62362}Nothing.
{62363}{62438}I'm getting|inconsistent life signs...
{62439}{62494}but they may be sensor ghosts.
{62561}{62589}Computer is still on.
{62629}{62687}I'll try the standard|docking codes.
{62688}{62738}Control codes confirmed.
{62739}{62780}Initiating docking sequence.
{62896}{62966}Weird.|What kind of ship is that?
{62967}{63014}That's not one of ours.
{63288}{63369}Boys, that's not even human.
{63410}{63451}If this is all a dream...
{63452}{63504}why can't there be more girls?
{63653}{63705}As part of her enslavement...
{63706}{63788}the brave young space captive|Penny Robinson...
{63789}{63947}is forced to utilize her|dazzling technical expertise.
{64162}{64191}Identify yourself, soldier.
{64192}{64280}West, Major,|United Global Space Force...
{64281}{64341}requesting permission|to see the prisoner.
{64438}{64546}Proceed, Major West.
{64804}{64862}Could he be cuter?
{64910}{64949}I don't think so.
{64950}{64997}Breathe, Penny.
{65102}{65130}Unlock.
{65358}{65401}These quarters are unacceptable.
{65402}{65472}We're going to check out|the probe ship.
{65473}{65544}Maybe we can figure out how they|got here and how to get home.
{65545}{65585}Have a wonderful trip.
{65635}{65663}Put this on.
{65770}{65812}You're coming with us.
{65813}{65898}Out of the question. I am|a doctor, not a space explorer.
{65899}{65961}What you are|is a murderous saboteur.
{65962}{65995}I am not leaving you here...
{65996}{66063}so you can do more harm|than you've already caused.
{66064}{66094}I absolutely refuse.
{66142}{66191}Give me an excuse to kill you.
{66226}{66258}Please?
{66444}{66510}Black was always my color.
{66606}{66633}Lock.
{66916}{66976}Activate standby.
{66977}{67039}Crush, kill, destroy.
{67115}{67158}Surprise.
{67159}{67192}Safety on.
{67222}{67271}Dad, chill.|It's OK.
{67272}{67336}I hacked into his CPU,|and then...
{67337}{67413}I bypassed|his main operating systems...
{67414}{67482}and accessed his subroutines.
{67483}{67555}He's basically just running|on remote control.
{67614}{67670}I know I haven't been around--
{67671}{67699}Professor.
{67739}{67772}We're ready to go.
{67826}{67871}We'll talk later, son.
{67980}{68028}Take care of my dad.
{68029}{68066}OK, Robot?
{68298}{68358}Vacuum check complete.
{68903}{68942}Oxygen levels are normal.
{68943}{68978}Microbe scans are negative.
{68979}{69017}Clear.
{69108}{69161}The air is stale, old.
{69162}{69224}That's the smell of ghosts.
{69284}{69355}I've got|her on-board computer up.
{69381}{69417}Not working?
{69418}{69451}She's working, all right.
{69452}{69489}Just--I don't know.
{69490}{69543}Too damn fast.
{70573}{70635}Dad, do you hear something?
{70636}{70686}Like the drip, drip of blood.
{70687}{70744}You really need to shut up.
{70786}{70813}Here.
{71082}{71131}This matter appears biological.
{71155}{71199}Nothing good will come of this.
{71200}{71272}You, of course, being the expert|on space exploration.
{71334}{71361}Let's go.
{71398}{71440}Trust me, Major.
{71470}{71541}Evil knows evil.
{72192}{72242}Motion sensors|are still working.
{72243}{72273}This way.
{72699}{72770}Rambler-crane series robots.
{72771}{72838}But like no design|I've ever seen.
{72839}{72879}Well, well.
{72905}{72957}Aren't we the poor cousin?
{72958}{72997}Down here.
{73207}{73254}It's a remote op station.
{73278}{73315}Come on, Dr. Smith.
{73381}{73428}Could this ship be a prototype?
{73454}{73505}Looks like some kind|of fire fight.
{73563}{73614}Captain's log is degraded.
{73639}{73724}Maybe I can gather|some fragments.
{73820}{73870}Sorry.
{73914}{73983}The hyperspace tracker seems|to be functioning normally...
{73984}{74065}but we cannot process|all the data.
{74098}{74175}There is no sign|of the Jupiter 2.
{74176}{74246}I have exceeded my timetable.
{74326}{74366}When did he make Major?
{74367}{74419}I want this on the record.
{74420}{74519}I am not willing to give up.
{74520}{74561}Don would come looking for me.
{74743}{74814}That's it. The rest|of the data's totally corrupted.
{74814}{74880}How could they launch|a rescue mission for us...
{74881}{74938}when we've only been lost a day?
{74939}{75016}There's no data|on the alien ship...
{75017}{75089}but they brought in something|that was attached to its hull.
{75137}{75165}Got it.
{75295}{75337}Some sort of egg sack?
{75625}{75652}Get back here!
{75653}{75733}Be happy to oblige...
{75734}{75792}although I don't think it's me|you should be worrying about...
{75793}{75832}but rather these.
{75990}{76029}I'm detecting motion.
{76030}{76069}Behind you.
{76125}{76153}After it. Move!
{76266}{76297}Bring Smith.
{76298}{76370}Don't even think about it.
{76842}{76877}Hydroponics.
{76878}{76950}Growth like this|would take decades.
{76988}{77048}Unhand me, you mechanical moron.
{77128}{77178}Don't move.
{77400}{77435}Easy.
{77436}{77491}Easy there, buddy.
{77492}{77538}No one's gonna hurt you.
{77588}{77641}Easy.
{77693}{77734}Relax.
{77887}{77931}Excellent.
{77932}{77993}Looks like you made a friend.
{77994}{78024}Still, I'd wait a few weeks...
{78025}{78074}before tattooing|her name on your arm.
{78130}{78170}Do yourself a favor.
{78171}{78200}Don't evolve.
{78229}{78289}Charming.
{78290}{78334}The Dr. Dolittle of outer space.
{78335}{78421}This could be a creature|from that alien ship.
{78422}{78465}But this guy's no pilot.
{78466}{78519}He looks like a child.
{78894}{78963}Try it now.
{79070}{79121}Strange.
{79122}{79185}The scales are giving off heat.
{79186}{79250}I've tapped into|the internal sensor array.
{79297}{79363}There's no other|animate life present.
{79364}{79440}Besides us,|this ship is totally deserted.
{79441}{79496}A ghost ship.
{79497}{79596}The flavor of the day|is banana beef.
{79646}{79707}Who thinks up|these combinations?
{79905}{79933}Good.
{79934}{80001}Major West, I highly|recommend you never breed.
{80033}{80111}That, by the way,|is my medical opinion.
{80595}{80634}Little thing was hungry.
{80635}{80685}I got their star maps on-line.
{80686}{80733}Here we go.
{80734}{80801}More systems|than I've ever seen.
{80802}{80880}Finding a route to Alpha Prime.
{80881}{80941}Downloading to Jupiter.
{81301}{81359}I don't like the sound|of that sound.
{81565}{81600}They're moving.
{81835}{81897}Get this infernal...
{81898}{81946}ape thing off me!
{81947}{81979}Come here.
{81980}{82048}John, get the hell out of there.
{82049}{82116}Mom says,|"Get the hell out of there."
{82812}{82844}Evacuate.
{82845}{82880}Now!
{83159}{83200}The controls are too slow.
{83201}{83242}Activate holographic interface.
{83243}{83314}Holographic interface, on-line.
{83857}{83919}They eat their wounded.
{84171}{84206}Seal the bulkhead.
{84249}{84277}Codes are locked.
{84407}{84446}Duck.
{84515}{84586}Closing bulkhead.
{84792}{84853}Fire sensor activated.
{84854}{84895}Emergency bulkhead closing.
{84956}{84993}Stop!
{84994}{85045}We have to get that door open.
{85197}{85224}Open, damn you!
{85225}{85281}Get out of here.
{85282}{85371}What is with me|and these damn doors?
{85372}{85442}I can't override|the fire protocol!
{85502}{85550}A million bucks|worth of weaponry...
{85579}{85626}and I'd trade it all back...
{85652}{85681}for a lousy...
{85718}{85748}can of Raid.
{86131}{86175}Stand clear.
{86508}{86561}Get moving! Go!
{86711}{86753}Come on!
{86754}{86821}Maureen...|can you get me anything?
{86822}{86876}Cycling through a vacuum check.|I'm overriding.
{87113}{87157}No way it's that easy.
{87886}{87923}Run!
{87975}{88040}Run! Get back!|Get back to the ship!
{88041}{88082}Move it!
{88390}{88433}Got it. Try it now.
{88434}{88489}Mom says, "Try it now."
{88826}{88860}Can we save it?
{88861}{88940}Can't without letting|the spiders into the ship.
{88941}{88983}Leave him behind!
{89170}{89255}That spider scratched me!
{89279}{89326}Stop laughing, you little worm.
{89616}{89644}Good-bye, Robot.
{89690}{89726}You couldn't save him, kid.
{89726}{89765}Save him? Of course.
{89916}{89944}What are you trying to do?
{90026}{90063}Hurry! Disengage!
{90284}{90337}This is a fun picnic.
{90338}{90414}First yellow aliens,|now giant spiders.
{90648}{90691}The crowd goes wild.
{90692}{90743}Recall your childhood|nightmares, Major.
{90744}{90786}Monsters are rarely|so easily dissuaded.
{90787}{90860}Why don't you talk to them,|bug to bug?
{90861}{90911}I think|they'd rather come inside.
{91132}{91176}Arming torpedoes.
{91223}{91251}Fire in the hole.
{91407}{91469}Alert. Detonation failure.
{91527}{91581}The robot must have damaged|the detonator cores.
{91582}{91626}They won't blow.
{91627}{91722}Alert.|Outer hub has been compromised.
{91750}{91812}DNA extrapolation coming up.
{91813}{91901}Silicone-based, mantium shell,|lack of respiratory system.
{91902}{91956}Means they do live|in deep space.
{92007}{92072}Tiny front brain implies|communal relationships.
{92073}{92101}Like beetles.
{92102}{92164}The biology lesson is over.|I could use some help.
{92165}{92231}They may be attracted|to heat and light.
{92278}{92364}Inner hull breach in 15 seconds.
{92365}{92417}I'm bringing the Proteus|fusion drives on-line.
{92731}{92758}It's working.
{92759}{92806}Let's turn up the heat.
{92807}{92835}What are you doing?
{92836}{92887}Never leave an enemy stronghold|intact.
{92888}{92916}Stop!
{92917}{92966}That's one of your father's|first rules of the game.
{92967}{92995}That is a direct order.
{92996}{93025}I hate spiders.
{93684}{93712}That's coming fast.
{93713}{93766}Get into the harnesses now.
{93767}{93823}Manual helm, engage.
{93862}{93912}-Children, secure?|-Secure.
{93913}{93941}I'm in.
{94407}{94454}Pull up.
{94455}{94496}Really? No kidding.|Thanks.
{94611}{94663}Coming in too hot.|I'll try and slow us down.
{95398}{95430}Hang on!
{95964}{95999}Everybody by the numbers.
{96000}{96040}Life sciences,|still breathing.
{96093}{96163}Video mechanics...|OK.
{96164}{96215}Mission medical, I'm alive.
{96216}{96262}Me, too.|Robotics, I mean.
{96263}{96302}I'm alive...
{96303}{96393}Major West's poor excuse for|piloting skills notwithstanding.
{96394}{96469}Oh, Dorothy.
{96470}{96512}Back in Kansas at last.
{97216}{97269}You violated a direct order.
{97301}{97359}About half the core|material's burned out.
{97360}{97403}We'll never generate|enough power to break orbit.
{97404}{97436}We can get off the ground...
{97437}{97497}but getting back into space|is another story.
{97498}{97594}I ordered you not to blow|that ship's reactors.
{97595}{97670}Life support is marginal.
{97671}{97703}It's gonna get cold in here|tonight.
{97704}{97812}Also, the pod and the chariot|are pretty much scrap metal.
{97813}{97858}Don't you walk away from me|when I'm talking to you.
{97859}{97906}Give it a rest, Professor.
{97907}{97952}I was technically|still in command.
{97953}{98017}I am commander of this mission.
{98018}{98053}Look, no offense...
{98054}{98117}but you're an egghead|with an honorary rank.
{98118}{98192}No one ever intended for you|to handle combat situations.
{98193}{98276}You handled it brilliantly,|sending us crashing down here.
{98277}{98357}Those aliens posed|a continuing threat.
{98358}{98394}I made a judgment call...
{98395}{98460}and, if I have to,|I'll make it again.
{98461}{98505}You of all people|should understand that.
{98506}{98539}Your father would back me up.
{98540}{98571}My father is dead...
{98572}{98681}killed in one of those combat|missions you admire so much.
{98682}{98743}My family is on this ship,|and you will follow my orders...
{98744}{98801}whether you agree with them|or not. Is that clear?
{98802}{98830}Save your speeches.
{98831}{98883}I like you, but I'm gonna|do whatever it takes...
{98884}{98923}to ensure the success|of this mission...
{98924}{98992}with or without your help.|Is that clear?
{98993}{99038}Am I interrupting something?
{99039}{99095}No, really.
{99096}{99152}I think you two|should slug it out.
{99202}{99269}Here we are,|stranded on an alien world...
{99270}{99321}and you want|to get into a pissing contest?
{99322}{99385}Please, go for it.
{99386}{99459}I'll have Judy down here|to declare you both unfit...
{99460}{99487}and I'll take over this mission.
{99488}{99569}I don't want to hear another|word from you. Is that clear?
{99593}{99667}Not...another word.
{99668}{99696}Better.
{99725}{99794}If you've finished hosing down|the decks with testosterone...
{99795}{99844}I suggest you come with me.
{99845}{99891}I may have found a way|off this planet.
{100013}{100057}Tell me about it.
{100989}{101028}Damn bug bite.
{101438}{101493}She...
{101494}{101588}She really is an interesting|specimen. Huh, doc?
{101590}{101624}She's fascinating.
{101662}{101707}The retinal aperture dilation...
{101708}{101773}seems directly linked|to the skin pigmentation.
{101846}{101874}What?
{101922}{101952}Can I keep her?
{102034}{102115}She's not just another fad|you can pick up and throw away.
{102116}{102176}Oh, please.
{102177}{102256}She's all alone here, and|I promise I'll look out for her.
{102257}{102299}I promise.
{102382}{102424}She kind of needs me.
{102532}{102584}The minute you misplace her,|you forget to feed her--
{102585}{102634}Don't smile. I mean it, Pen.
{102666}{102710}Thanks...doc.
{102787}{102885}We're both a long way from home,|aren't we, little one?
{102984}{103012}Blarp?
{103136}{103197}That's what we'll call you--|Blarp.
{103346}{103380}Nice girl.
{103381}{103421}Pretty girl.
{103618}{103646}Nice.
{103742}{103833}The atmosphere here|can sustain human life.
{103834}{103916}I've located 500 rads|of radioactive material...
{103918}{103964}five miles west.
{103965}{104033}We'll need at least that much to|get the core functioning again.
{104062}{104095}We start out at daybreak.
{104184}{104216}Be safer that way.
{104289}{104335}Those are my orders.
{104530}{104586}I agree|with your recommendation.
{104621}{104661}Detente's a beautiful thing.
{104846}{104910}It's nice to see you found|a corner to suit your talents.
{104911}{104961}Turn down the bed|before you leave.
{104962}{105016}I gave my word I'd let you live.
{105054}{105085}I never said for how long.
{105086}{105162}Family hour is over.
{105163}{105211}We're dying here.
{105212}{105291}Robinson is out of his league.
{105292}{105401}Look into his eyes and tell me|you can't see his fear.
{105464}{105534}I fought in the millennial wars.
{105534}{105574}Survival is a soldier's game.
{105575}{105668}We both know this civilian fool|will lead us straight to hell.
{105669}{105795}Robinson needs our help,|if he wants it or not.
{105796}{105856}With minimal force,|we could take this ship...
{105858}{105925}and assure them we shall|continue at your command.
{105954}{105994}Of course.
{105995}{106054}My God...
{106055}{106103}you're right.
{106104}{106165}How could I have been so blind?
{106166}{106297}I'll just run and get you a gun|so we can hijack the ship, OK?
{106346}{106416}Sarcasm is the recourse|of the weak mind.
{106453}{106506}I'm hiding the pain.
{106507}{106535}Really.
{106616}{106645}Lock.
{106742}{106829}Your pain...
{106830}{106863}has just begun.
{106992}{107031}Starlight, star bright.
{107126}{107203}A million strange stars,|and only one wish.
{107204}{107239}I wish we were home.
{107306}{107371}Never seen a sky look so alien.
{107372}{107429}We really are lost,|aren't we?
{107570}{107652}When the first sailors|circled the globe...
{107653}{107727}saw a brand-new sky...
{107728}{107809}they thought they'd sailed|off the edge of the earth...
{107810}{107850}but they were really|just around the corner.
{107910}{107962}You're saying we should|just billow our sails...
{107963}{108002}and let the wind take us home?
{108003}{108035}Is that it?
{108082}{108121}Those sailors...
{108165}{108253}found familiar shapes...
{108254}{108312}in the stars...
{108313}{108391}to make the sky seem|more friendly...
{108392}{108426}and to help them|find their way home.
{108427}{108496}That's how the constellations|were born.
{108550}{108604}Porky, the wise and mighty pig.
{109030}{109131}The great...|big-eared bunny Bugs.
{109380}{109452}The way you got us down here,|that was pretty flying.
{109630}{109679}My quarters or yours?
{109700}{109729}Excuse me?
{109730}{109794}Don't play coy.
{109795}{109878}We're the only single people|of consenting age in the galaxy.
{109879}{109933}How much more of a setup|do you need?
{109974}{110056}So you figure, why not dispense|with the pleasantries...
{110058}{110093}and get down to business?
{110094}{110169}You have a way with words.
{110214}{110259}Do you want to show me|how you handle the helm?
{110376}{110433}Right here on this console?
{110540}{110600}Right here would be fine.
{110837}{110901}Why don't you just hang on|to your joystick?
{111135}{111182}Excellent technique, Major.
{111222}{111251}Really.
{111365}{111403}Hi.
{111404}{111445}Will was looking for you.
{111510}{111551}I sent him back to his room.
{111552}{111636}He's decided|he can rebuild the robot.
{111686}{111742}He wants to stay up all night|and show me his designs.
{111775}{111833}Funny creatures, men.
{111834}{111910}Try so hard not to be|their fathers...
{111911}{111977}end up making the same mistakes.
{111978}{112098}We can't get off this planet,|let alone get back on course.
{112099}{112134}I don't have time.
{112135}{112182}Just listen to him.
{112182}{112258}It doesn't matter what he says.|Just listen.
{112259}{112344}Sometimes--especially|in the eyes of their fathers--
{112345}{112411}Iittle boys have to come first.
{112412}{112485}As soon as|we get back up into space...
{112486}{112574}we'll spend a lot of time|together, I promise.
{113051}{113119}It's nice having your|whole family under one roof.
{113175}{113234}Even if we did have to go...
{113235}{113301}halfway across the galaxy|to manage it.
{113616}{113650}Good night, John.
{113651}{113685}Good night, Maureen.
{113686}{113740}Good night, Judy.
{113741}{113773}Good night, Will.
{113795}{113827}Good night, Penny.
{113886}{113945}You guys have got to be kidding.
{114093}{114149}Good morning, Will Robinson.
{114150}{114225}Solar panels are charged.
{114642}{114705}The radioactive material|we need for the core...
{114706}{114748}is in the center of that bubble.
{114749}{114784}I was afraid of this.
{114818}{114881}OK, everybody,|let's get settled now.
{114952}{115016}I think this "bubble"|out there...
{115017}{115099}is exactly the same thing|we passed through in space.
{115100}{115208}Both of them are opening|and closing doorways.
{115210}{115254}Doorways to where?
{115255}{115345}Doorways in...time.
{115346}{115379}You can't be serious.
{115380}{115431}Time travel is impossible.
{115432}{115487}It's not.|Just improbable.
{115488}{115581}What if we crossed|into a time...
{115582}{115652}years after Earth|sent a rescue mission?
{115653}{115709}Perhaps the professor|hit his head when we landed.
{115710}{115740}Think about it.
{115741}{115815}The way the Proteus|seemed deserted for so long.
{115816}{115888}Your friend looking so old.
{115889}{115944}So if we walk|inside that bubble...
{115945}{116007}we could be walking|further into the future.
{116008}{116099}Dad, what if the doorways|aren't natural?
{116100}{116181}This kind of phenomenon could|only be produced naturally.
{116182}{116237}That bubble's|the kind of side effect...
{116238}{116305}I predicted my time machine|would do.
{116306}{116348}What if someone built a device--
{116349}{116429}Son...|I appreciate your input...
{116430}{116474}but now is not the time|for flights of fancy.
{116475}{116545}You never listen to me.
{116578}{116617}Not ever.
{116826}{116918}This time bubble could be|causing these earthquakes.
{116919}{117023}No telling how long before|this planet breaks up entirely.
{117024}{117077}The major and I|are going to locate...
{117078}{117123}the radioactive material|for the core.
{117155}{117207}We may have very little time.
{117479}{117519}I'm leaving now.
{117520}{117562}That's a surprise.
{117689}{117789}You're the most important thing|in the world to me.
{117790}{117873}One day, I hope you'll|be able to understand that.
{117874}{117982}What if...|one time you don't come home?
{118074}{118132}Whenever your grandfather|went on a mission...
{118333}{118414}he'd leave these with me|for safekeeping.
{118443}{118526}When he came home,|I would always be there...
{118527}{118598}waiting to give them back.
{118665}{118705}I'm coming back.
{118752}{118783}I promise.
{119367}{119398}Listen...
{119446}{119478}about last night...
{119512}{119572}Go on. You can do it.
{119611}{119638}I'm sorry.
{119639}{119717}See, that wasn't so difficult.
{119718}{119796}Like pulling steel needles|through my cheeks.
{119797}{119930}Then you understand|what saying this feels like.
{119931}{119985}Try to come back in one piece.
{120092}{120144}Listen, doc, I'm...
{120182}{120252}I'm thinking this is your basic|"kiss for luck" occasion.
{120253}{120291}Wouldn't you agree?
{120292}{120337}Thinking.
{120338}{120391}It's not really|your strong suit, is it?
{120503}{120563}I've got a fix|on the radioactive material.
{120891}{120941}That was scientific.
{120971}{121002}Scared?
{121040}{121087}There's an alloy|in this crater wall...
{121088}{121123}that's disabling the com-links.
{121124}{121177}You're not going to be able|to communicate with the ship.
{121298}{121350}Come home to me, professor.
{121400}{121445}I love you, wife.
{121580}{121615}Come here, squirt.
{121908}{121980}Nice girl.|Pretty girl. Nice.
{122718}{122773}It's OK.|You're still in one piece.
{122904}{122932}Come on.
{123034}{123123}Can you hear me, Robot?|Hello?
{123152}{123179}Systems error!
{123180}{123233}Robot unable to locate|motor controls!
{123234}{123265}Unable to--
{123266}{123293}Calm down.
{123294}{123362}What is happening to me?
{123363}{123460}I didn't have enough time|to finish the download.
{123461}{123508}Warning!|Penny, give it back!
{123509}{123563}My circuits are unbalanced.
{123564}{123627}So I had to finish you off|with another personality.
{123628}{123673}I put my mind inside of yours.
{123804}{123875}That explains|this warm fuzzy feeling...
{123876}{123931}when I think about baseball.
{123932}{123979}Strike! You're out!
{123980}{124021}But this does not compute.
{124022}{124051}What?
{124052}{124128}Robot tried to destroy|the Robinson family.
{124129}{124198}Why did Will Robinson|save Robot's personality?
{124199}{124294}I guess sometimes friendship|means listening to your heart...
{124294}{124325}not your head.
{124326}{124378}Put that in your memory bank.
{124422}{124471}Don't worry.
{124523}{124563}I'm going to build you|a new body.
{124605}{124664}Mom always said I should|try to make new friends.
{124865}{124923}I need a microsealer.
{124924}{124957}I got it.
{125123}{125168}After much deliberation...
{125169}{125224}the space captive|has finally decided...
{125225}{125313}to accept her new role|as a member of the crew.
{125314}{125389}The Robinsons, after all,|can obviously use her help.
{125453}{125495}Blarp, come back here.
{125496}{125565}Theoretically,|this future would be fixed...
{125566}{125627}unchanged by what we do|or did in the past--
{125628}{125684}Professor?
{125685}{125741}Why don't you give|the old egghead a rest?
{125742}{125850}Out here we got two moons,|a crater the size of Miami...
{125851}{125933}and that would be|one great climb.
{125934}{125981}My father would have liked you.
{126109}{126137}What's that?
{126398}{126443}This metal's decades old.
{126444}{126499}What kind of a nightmare|is this?
{126542}{126570}Where the hell are we?
{126571}{126625}The question is,|when the hell are we?
{127141}{127235}I will tell you a joke.
{127236}{127300}Why did the robot|cross the road?
{127301}{127377}Because he was carbon-bonded|to the chicken.
{127378}{127421}We have a lot of work to do.
{127507}{127566}That sounds like old Morse code.
{127567}{127602}What does it say?
{127603}{127661}"Danger,|Will Robinson, danger."
{128257}{128306}William. Come in.
{128344}{128377}Unlock.
{128468}{128509}You said someone was in danger.
{128510}{128555}We all are.
{128556}{128606}You are wise to arm yourself.
{128607}{128678}This gun is set to fire|for me only...
{128679}{128752}so don't try anything funny.|Lock.
{128834}{128937}You misjudge me.|I only want to help you.
{128938}{129003}Help us?|You tried to kill us.
{129004}{129063}But now our fates|are intertwined.
{129064}{129153}If your father|and that idiot West fail...
{129154}{129222}I have no chance|of getting home.
{129223}{129331}It's in my best interests|that they succeed...
{129332}{129416}and I always follow|my best interests.
{129481}{129666}What monsters roam|these alien wilds?
{129667}{129727}They're fools!
{129728}{129821}To set off blindly|across this savage land.
{129873}{129915}Much as I hate to admit it...
{129953}{130030}it will be much harder|without them.
{130031}{130083}What are you talking about?
{130084}{130161}They'll be back.|They'll be OK.
{130218}{130245}Will they?
{130325}{130372}Someone should go after them.
{130373}{130400}Unlock.
{130401}{130444}I forbid it. You're a boy.
{130445}{130486}A clever one,|but a child nonetheless.
{130487}{130551}This planet|is likely full of predators.
{130552}{130655}Even if you found them,|what if they're hurt? Ravaged?
{130762}{130789}Dying?
{130869}{130906}What good could you do?
{131002}{131078}You can help them.|You're a doctor.
{131254}{131301}I'm a doctor.
{131346}{131388}We made it.
{131389}{131451}Mom didn't see us.
{131452}{131505}That's fantastic.
{131565}{131619}I told them we could get|into the bubble this way.
{131774}{131803}The bubble's growing!
{131906}{131984}Run, child!
{132370}{132425}Cool.
{132426}{132467}Wait!
{132618}{132709}Come on.|We can always go back.
{132710}{132770}It's just like stepping|between two rooms.
{132771}{132818}I can barely contain my glee.
{132847}{132927}Dad's signal is...|this way.
{133015}{133060}I loathe children.
{133550}{133623}Billy...kissing...
{133624}{133749}hot wings, orchids, corn.
{133781}{133958}Waves...Billy...|popcorn with...kissing...
{133959}{134049}What did you find?
{134050}{134127}Come on.|No time to dawdle.
{134128}{134197}Let's move along.
{134245}{134304}Follow your father's signal.|There's a good boy.
{134336}{134366}Come on.
{135062}{135181}All things really do come|to he who waits.
{135415}{135446}What is this place?
{135447}{135511}The shock must have|scrambled your brain.
{135512}{135565}Take a look around.
{135677}{135727}Don't you recognize this spot?
{135833}{135885}You're home.
{136023}{136055}This can't be.
{136056}{136118}What have you done to the ship?
{136153}{136196}Where is my family?
{136226}{136317}What chance do you think|your family had without you?
{136318}{136411}A few spiders survived|the destruction of the Proteus.
{136412}{136481}They reached this planet and...
{136600}{136665}I can still hear|the women scream.
{136766}{136794}Who are you?
{136795}{136829}You don't recognize me?
{137020}{137085}I'm your son Will.
{137194}{137248}Dad's signal|is just over this ridge.
{137249}{137329}Be still, my foolish heart.
{137330}{137379}Shit.
{137380}{137459}A boy of your intelligence|should never swear.
{137534}{137573}Shit.
{137661}{137699}Indeed.
{137802}{137847}Look, Father...
{137848}{137973}what my flights of fancy|have wrought.
{138010}{138110}I used your hyper engine|to build my time machine.
{138162}{138210}OK, Robot, put him down.
{138211}{138251}Affirmative.
{138396}{138429}Where are we?
{138430}{138501}I think the Jupiter 2,|but in a different future.
{138502}{138548}Father?
{138549}{138579}Once this core material...
{138580}{138659}is fully introduced|into the control console...
{138660}{138715}Core material.
{138716}{138785}If we could get that|back to our Jupiter...
{138786}{138920}I will open a doorway|stable enough...
{138921}{139045}for one person to take|one trip through time...
{139046}{139101}and space as well.
{139102}{139176}Commence proto-generation.
{139208}{139262}Cool, huh?
{139263}{139350}Today, I will change history.
{139402}{139475}I'm gonna go back to that day|you dragged us into space.
{139511}{139569}I'll stop the ship|from taking off.
{139649}{139699}I'll save the family.
{139700}{139777}Earth, October 1, 2058.
{139778}{139820}Target lock confirmed.
{139821}{139848}Excellent.
{139849}{139884}Son...
{139914}{139971}Look around.
{139972}{140064}The force of your time machine|is ripping this planet apart.
{140065}{140124}These violent distortions|in time...
{140126}{140176}are being caused|by your experiment.
{140177}{140260}What if it has the same effect|on Earth?
{140262}{140309}What if, in getting home...
{140310}{140362}you destroy Earth|in the process?
{140538}{140578}I know you mean well.
{140579}{140663}I'm going home.
{140664}{140708}I'm going to save the family.
{140709}{140785}You've got to listen to me.|I'm your father!
{140817}{140855}My father?
{140904}{140970}Let me tell you about my father.
{140971}{141048}I'll never forget|that morning 20 years ago.
{141049}{141109}What was it you said?
{141110}{141174}"l'm coming back.|I promise."
{141175}{141235}You promised...|and you never came home.
{141236}{141329}My father's not|coming to the rescue.
{141918}{141968}What do you think you're doing,|young man?
{141969}{142021}Let me tell you about life.
{142022}{142069}Around every corner,|monsters wait.
{142070}{142106}I know. I am one.
{142107}{142190}We monsters have no fear|in devouring little boys.
{142191}{142251}To survive, you must be|fully prepared to kill.
{142252}{142297}I can do it.
{142298}{142326}Can you?
{142394}{142452}Listen to me, my child...
{142453}{142504}I've crossed this world|with you...
{142505}{142605}risked my life,|but I would not throw it away.
{142606}{142676}Who knows what dangers|lie ahead?
{142711}{142742}You can't protect us.
{142780}{142808}I can.
{142848}{142876}I will.
{142928}{142985}Gimme the gun.
{142986}{143034}Enable gun for all users.
{143035}{143076}Voiceprint confirmed.
{143118}{143207}A brief lesson in survival|on this world or any other--
{143208}{143297}never trust anyone.|Especially me.
{143401}{143477}It's almost time.|I hope it works.
{143478}{143505}Never fear...
{143533}{143561}Smith is here.
{143587}{143645}Don't move,|Professor Robinson...
{143646}{143740}or this peculiar family reunion|will be tragically brief.
{143742}{143785}I'll ask you|to step away from that.
{143786}{143835}It's a time machine,|you idiot.
{143836}{143911}I had hoped to take over|the ship with this.
{143912}{143989}One of life's little ironies.
{143990}{144070}Let's try this dance again.
{144071}{144132}You are the puppet,|I am the puppeteer.
{144134}{144226}Do try to get it right|this time.
{144227}{144309}Robot, you will respond|to my voice alone.
{144310}{144342}Affirmative.
{144343}{144394}We need electric disrupters.
{144476}{144526}That's good I met you.
{144579}{144659}You did it.|Just like I imagined.
{144660}{144707}You linked|the dimensional sifter...
{144708}{144744}to the navigational array.
{144745}{144816}That's how it can be in|the same place at the same time.
{144818}{144938}But the spatial delivery system,|the targeting laser...
{144939}{144976}I never thought of those.
{144978}{145080}The future is never what|it seems like when you're 10.
{145081}{145160}Say good-bye to your past!
{145161}{145223}Your future lies with me.
{145224}{145272}I'm going home in your place.
{145342}{145387}What are you grinning at?
{145438}{145563}Look around you...|at this hostile world.
{145564}{145645}Do you think a boy|could have survived all alone?
{145671}{145736}Never fear...|Smith is here.
{145774}{145815}It's Dr. Smith.
{145816}{145858}Hello.
{145859}{145952}How nice to see me again|after all these years.
{145953}{146008}Confused?|Have I changed?
{146009}{146103}The spider's sting had some|unexpected side effects.
{146104}{146175}My unique gifts|gave me an advantage...
{146176}{146236}in this quarrelsome world.
{146237}{146298}After the women were savaged...
{146299}{146421}I became the father|Will never had.
{146422}{146573}Two decades of agony taught me|the error of my ways.
{146574}{146704}But you, your crude ambition|fills me with self-loathing.
{146706}{146788}You see,|I have looked within me...
{146789}{146843}and what I see is you!
{147041}{147121}I never liked me anyway.
{147122}{147176}Robot, kill them all.
{147200}{147232}Wait.
{147233}{147287}Dr. Smith, please.
{147350}{147397}Don't.
{147546}{147599}Very well.
{147600}{147676}Robot, take them inside|and keep them there.
{147677}{147762}If they move...|then kill them.
{147763}{147837}Proceed or be destroyed.
{148386}{148415}Nothing works.
{148473}{148533}I'll draw his fire,|you grab Will and get out.
{148534}{148561}Halt!
{148590}{148626}Stop!
{148663}{148717}Do you remember me?
{148717}{148797}Do you remember what I|taught you about friendship?
{148882}{148963}I need you to help us now,|because we're friends.
{148964}{149033}Logic error.|Friendship does not compute.
{149034}{149114}Forget logic.|Act with your heart.
{149115}{149188}Robot has no heart.
{149190}{149250}Robot is powered by|a fusion pulse generator.
{149251}{149292}Every living thing has a heart.
{149293}{149373}My programming has been modified|to remove all emotion.
{149374}{149429}Any attempts to override|command protocols...
{149430}{149478}may result in fusing|my neural net.
{149577}{149608}Please, Robot?
{149609}{149665}If you don't let us go,|we're all gonna die.
{149666}{149735}I'm asking you now,|will you help us?
{149773}{149808}Will you be my friend?
{149909}{149977}Robot attempting|to deactivate control bolt.
{149978}{150040}-Commands overridden!|-Do it!
{150041}{150100}Destroy Robinson family!
{150102}{150145}Destroy!
{150393}{150424}You did it.
{150482}{150534}Robot will save Will Robinson.
{150535}{150593}Robot will save his friend.
{150686}{150745}Where are they?
{151063}{151090}Wait here.
{151128}{151163}Without that core...
{151164}{151217}I can't promise|we'll get off this rock.
{151218}{151283}See if you can make it|back to our Jupiter.
{151284}{151321}I'll get the core material|and meet you there.
{151322}{151372}We don't have the trackers|to find our way back.
{151373}{151432}The family needs their father.
{151433}{151482}The crew needs their pilot.
{151483}{151568}I can't fly the ship|as well as you can.
{151569}{151635}You're their best chance|to survive.
{151636}{151685}Listen to me.
{151686}{151748}I know you never wanted|to take this job.
{151750}{151841}I think you're going to turn out|to be a grade-A baby-sitter.
{151842}{151943}So...|the camper's all yours now.
{151944}{151974}Take care of them.
{152001}{152039}Good luck.
{152040}{152070}-Dad!|-Professor!
{152148}{152229}Remember the space spiders|in the Proteus?
{152318}{152349}They're not going to be able|to get back.
{152440}{152476}Enable all missiles.
{152522}{152560}But the warheads don't work.
{152561}{152589}Just do it.
{152646}{152681}Look!
{152802}{152865}Damn, he's still breathing.
{152944}{152974}Fire in the hole.
{153130}{153213}So these sailors,|they drew shapes in the sky...
{153270}{153328}Look! It's a flare!
{153374}{153420}...to help them|find their way home.
{153421}{153460}Danger, Will Robinson!
{153838}{153913}Climb on! Hurry!
{154137}{154210}Field dampeners on-line.
{154211}{154269}Portal compression commenced.
{154492}{154604}Tell me again, old monster,|how did the girls die?
{154605}{154684}We've been over this before,|son.
{154764}{154805}In all the years since...
{154869}{154929}the spiders|have never resurfaced.
{154998}{155035}Why?
{155036}{155153}Let's forget the past.
{155243}{155335}Portal aperture reduction, 50 % .
{155457}{155529}Careful, child!|The plasma around the portal...
{155529}{155582}will rip a man into pieces!
{155718}{155827}Haven't you made the doorway...|too small?
{155828}{155859}Not for me.
{155893}{155967}But then I'm not going, am I?
{155968}{156028}Spiders didn't kill the girls.
{156070}{156101}It was you.
{156102}{156183}I just never let myself see it.
{156184}{156262}You kept me alive|because you needed me.
{156263}{156329}Because I could|build this for you.
{156357}{156412}Poor boy.
{156413}{156524}Did you really think|I would let you go?
{156525}{156652}Let all that I have become|vanish?
{156653}{156724}Look at me!|I am no mere man!
{156726}{156843}I...am...a...god!
{156844}{156909}Within these egg sacs|grow the seeds...
{156909}{156975}of a master race of spiders.
{156976}{157045}We shall descend upon|helpless Earth...
{157045}{157093}an entire planet to rule!
{157094}{157169}An entire planet|on which to feed!
{157213}{157287}Time to die...son.
{157288}{157335}I'm not your son.
{157336}{157394}Good-bye.
{157689}{157713}My father once said...
{157764}{157815}Evil always finds its true form.
{157843}{157903}You should have killed me|when you had the chance.
{157904}{157967}You were right.|I couldn't kill the man...
{157998}{158037}but I can kill the monster!
{158133}{158212}Spare me|the fuming of the righteous.
{158245}{158352}I think there's time for a snack|before my trip.
{158518}{158554}The pain.
{158601}{158649}You ain't seen nothing yet.
{158842}{158894}Remember the Proteus?
{158895}{158944}These monsters|eat their wounded.
{159267}{159345}Take all the time you want|to die!
{160122}{160207}Wake up, son!
{160208}{160236}Dad?
{160403}{160479}Core material insertion|complete.
{160525}{160617}All table run--2058.
{160617}{160646}Mission control.
{160647}{160730}You could've taken the core|and left before it was too late.
{160731}{160801}I couldn't let you fall.
{160802}{160833}You're my boy.
{161027}{161077}Mom ! It's them.
{161225}{161260}Oh, Mom !
{161310}{161336}You all right?
{161337}{161370}You're not as dumb as you look.
{161371}{161413}I'm going to get your name|tattooed right here.
{161454}{161504}Greetings.
{161505}{161541}Where's John?
{161615}{161649}The bubble closed behind us.
{161649}{161732}It was his only way back.
{161733}{161780}I'm sorry.
{161835}{161908}We've already begun|the preflight countdown.
{161909}{161960}I'm going to save|as many lives as I can.
{162249}{162302}I kept hoping somehow|he'd make it back.
{162458}{162493}Let's go, Major.
{162525}{162569}Good-bye, my love.
{162569}{162629}Engaging primary thrusters now.
{163521}{163584}Look. He made it.
{163887}{163945}Go.
{164124}{164160}We're not getting any altitude.
{164161}{164226}We don't have enough power.
{164448}{164477}I'm sorry.
{164907}{164955}I couldn't save them.
{165074}{165152}So many years ago.
{165153}{165200}I can still feel it--
{165201}{165241}our sun...
{165269}{165306}our Earth.
{165358}{165451}It's all I've thought about--|going home.
{165550}{165593}A long time ago,|you told a small boy...
{165594}{165690}that one day he'd understand|how much his father loved him.
{165749}{165829}I could never see|how much you cared...
{165897}{165941}until now.
{165942}{165969}Come.
{165970}{166022}Let's go.
{166089}{166159}I kept hoping he'd make it back.
{166160}{166201}Good-bye, my love.
{166282}{166310}Look!
{166348}{166420}Don't make me wait another|lifetime to know how you feel.
{166652}{166703}Dad!
{166818}{166915}Dad, it worked!
{166944}{166976}Come with us!
{166977}{167036}I can't.
{167037}{167126}Only enough power for|one person, one trip, remember?
{167258}{167313}It's good to see you again, Mom.
{167314}{167375}It's good to see you all.
{167376}{167425}Take care of them, Will.
{167601}{167656}Don't forget me.
{167684}{167734}He sacrificed everything|for his family.
{167918}{167953}I'm glad you came back.
{167994}{168060}I just want you to know|I love you.
{168099}{168159}I love you very much.
{168333}{168407}The planet|is breaking up around us.
{168561}{168625}We're doomed!
{168737}{168775}Boy, that felt good.
{168776}{168819}Get us airborne.
{168861}{168943}I'm going to try|to reach escape velocity.
{168944}{168983}We don't have the core material.
{168984}{169025}The gravity wells|will pull us back down.
{169025}{169064}We might be able to--
{169065}{169129}We won't make it. I know.
{169163}{169194}We have to go...
{169245}{169290}down--
{169291}{169356}through the planet|as she's breaking up.
{169357}{169443}We can use|the planet's gravity...
{169444}{169471}What?
{169472}{169552}to throw us out the other side|and back into space.
{169553}{169583}That's insane.
{169584}{169635}I don't have time to argue.
{169741}{169782}That's a direct order.
{169841}{169880}Yes, sir, commander.
{169913}{169976}This should be interesting.
{170741}{170770}I see it.
{170771}{170799}Full burn.
{171048}{171075}Stop!
{171076}{171105}-Right!|-Left!
{171105}{171133}Let me drive.
{171325}{171395}All right, everybody,|hold your noses.
{171915}{171970}Rock and roll.
{172683}{172740}Amazing.
{172911}{172964}Nice work, flyboy.
{172965}{173028}I earn that kiss yet?
{173029}{173064}You earn this.
{173228}{173276}This one's on credit.
{173497}{173532}Cold fish, huh?
{173993}{174053}There you are. Come here.
{174077}{174169}Where have you been,|you little creep?
{174170}{174218}-Little creep?|-Oh, great.
{174219}{174254}Warning, Major West.
{174255}{174326}My sensors indicate|we have a problem.
{174431}{174499}The planet's gravity field|is collapsing.
{174500}{174530}We'll be sucked in.
{174531}{174568}No way to get clear in time.
{174569}{174615}The hyperdrive.
{174616}{174676}I'm accessing|the Proteus star maps.
{174677}{174712}Here we go again.
{174713}{174772}Targeting Alpha Prime...|I hope.
{174816}{174872}Initiate...now.
{174873}{174900}Cool.
{174925}{175000}
