{1}{0}}25
{0}{0}Vyšlete jezdce na worzích.|{worgové}
{430}{505}Hej Sméagole, nechoï pøíliš vepøedu!
{505}{581}-Proè to dìláš?|-Co?
{581}{657}Nadáváš mu, mluvíš o nìm jako o stvùøe!
{657}{733}Protoe...
{733}{809}Protoe on takovı je, pane Frodo...
{809}{859}Nezbylo v nìm nic ne li a podvody.
{859}{986}-Chce Prsten, to je vše na èem mu záleí.|-Nemáš pøedstavu o tom co mu udìlal.
{986}{1112}Co mu stálì dìlá!
{1112}{1340}-Chci mu pomoct Same...|-Proè?
{1340}{1542}Protoe musím vìøit, e se mùe vrátit...
{1542}{1618}-Nemùete ho zachránit, pane Frodo...|-Co o tom ty mùeš vìdìt!
{1618}{1820}Nic!
{1820}{1946}Promiò Same...|Nevím proè jsem to øekl.
{1946}{2022}Já vím...
{2022}{2098}To ten prsten...
{2098}{2149}Nemùeš z nìj spustit oèi...
{2149}{2224}Vidìl jsem vás...
{2224}{2351}Nejíte, sotva spíte...
{2351}{2427}Zaèíná vás ovládat, pane Frodo,
{2427}{2477}-Musíte s tím bojovat!|-Vím co mám dìlat, Same!
{2477}{2578}Prsten byl svìøen mì!|Je to mùj úkol!
{2578}{2629}Mùj, mùj vlastní!
{2629}{2983}Copak se neslyšíte?|Nevíte jak to zní?!
{2983}{3134}Chceme ho...|Potøebujeme ho...
{3134}{3261}Musíme mít miláška...
{3261}{3337}Ukradli nám ho...
{3337}{3438}Mazaní malí hobiti...
{3438}{3539}Zlí, lstiví, špatní!
{3539}{3741}-Ne, ne.... pán ne...|-Ano! Milášek, falešnı!
{3741}{3868}Podvedou tì, zraní, oklamou...
{3868}{3994}-Pán je mùj pøítel.|-Nemáš ádné pøátele.
{3994}{4146}-Tebe nemá nikdo rád.|-Neposlouchám tì, neposlouchám.
{4146}{4348}-Jsi lháø a zlodìj...|-Ne.
{4348}{4474}Vrah...
{4474}{4626}-Vyhráls.|-Jsi pryè.
{4626}{4702}Nenávidím tì...
{4702}{4803}-Nenávidím tì...|-Kde bys byl nebıt mì?
{4803}{4904}Glum, Glume,|já jsem nás zachránil!
{4904}{5056}Byl jsem to já...|Pøeili jsme díky mnì!
{5056}{5157}U ne...
{5157}{5258}Co jsi øíkal?
{5258}{5384}Teï u se o nás stará pán...
{5384}{5460}U tì nepotøebujeme...
{5460}{5536}Coe?
{5536}{5713}-Odejdi a u nikdy se nevracej.|-Ne!
{5713}{5865}Odejdi a u nikdy se nevracej!
{5865}{6320}Odejdi a u nikdy se nevracej!
{6320}{6395}Øekli jsme mu aby šel pryè...
{6395}{6522}A pryè on odešel!|Pryè, pryè, pryè!
{6522}{6699}Sméagol je volnı!
{6699}{6749}Podívej!
{6749}{7204}Podívej!|Vidí co Sméagol našel?!
{7204}{7356}Dobrı dobrı králík!|Jezte, jezte!
{7356}{7432}Dìlá se mu z tebe špatnì...
{7432}{7558}Kdy se takhle chováš.
{7558}{7710}Je jenom jeden zpùsob,|jak sníst tyto králíky.
{7710}{7836}Co to dìlá?!|Hloupı, tlustı hobit!
{7836}{7912}Nièíš to!
{7912}{8114}Co se dá nièit?|Vdy na nìm je sotva trochu masa.
{8114}{8190}Potøebujeme pár dobrıch brambor.
{8190}{8266}Co je brambor, milášek?
{8266}{8367}-Co je brambor?|-BRAMBORY!
{8367}{8494}Uvaøit, nakrájet, napíchnout na tyèku.
{8494}{8671}Krásné zlaté køupavé...|S kouskem krásnì usmaené ryby.
{8671}{8797}-Ani ty bys to nemohl odmítnout.|-Ale ano mohl.
{8797}{8898}Tak zkazit krásnou rybu.
{8898}{9050}Dej nám ji...|Syrová a tøesoucí se...
{9050}{9151}A nech si hnusné brambory.
{9151}{9505}Jsi beznadìjnı.
{9505}{10010}Pane Frodo?!
{10010}{10162}-Kdo to je?|-Zlí lidé, sluebníci Saurona...
{10162}{10314}Jdou do Mordoru.|Temnı pán k sobì shromaïuje všechny armády.
{10314}{10415}U to enbude trvat dlouho.|Brzy bude pøipravenı.
{10415}{10516}-Pøipravenı na co?|-Aby rozpoutal válku.
{10516}{10693}-Poslední válku, která pokryje celı svìt stínem.|-Musíme jít.
{10693}{10794}-Pojï Same.|-Pane Frodo!
{10794}{10920}Podívejte!
{10920}{11173}To je olifant!
{11173}{11552}Nikdo doma tomu nebude vìøit...
{11552}{12614}Sméagole?
{12614}{12740}Zùstali jsme tu pøíliš dlouho.
{12740}{12842}Pojï Same!
{12842}{13195}Stùj!
{13195}{13474}Svate jim ruce.
{13474}{13549}Není divné, e jste nevidìla ádné trpaslice...
{13549}{13650}Vlastnì jsou hlasem i vousy podobné trpaslíkùm,
{13650}{13726}e byste si je mohla snadno splést s mui...
{13726}{13777}To ty vousy.
{13777}{13903}Z èeho povstala povìra,|e nejsou ádné trpaslice...
{13903}{14055}A trpaslíci prostì|vyskakují z dìr v zemi.
{14055}{14257}Co je samozøejmì smìšné...
{14257}{14333}Všechno je v poøádku, všechno je v poøádku,|nikdo nepanikaøte!
{14333}{14864}To bylo úmyslnì, to bylo naschvál.
{14864}{14990}Svìtlo veèernice nezhasne ani nezbledne...
{14990}{15117}Je to moje a mohu to dát komu chci...
{15117}{15218}Jako mé srdce...
{15218}{15521}-Jdi spát...|-Spím...
{15521}{15622}Tohle je sen...
{15622}{16001}Potom je to dobrı sen...
{16001}{16684}Spi...
{16684}{16785}Kdysi jsi mi øekla...
{16785}{16861}e pøijde tento den...
{16861}{16937}To není konec...|To je zaèátek.
{16937}{17013}Musíš jít s Frodem.
{17013}{17316}To je tvá cesta.
{17316}{17417}Má cesta je pøede mnou skryta.
{17417}{17493}Ji je pøipravena pøed tvıma nohama.|[Si peliannen i bad na dail lin.]
{17493}{17645}Teï nesmíš váhat.|[Si buiad u-dhan a thar.]
{17645}{17746}Arwen...
{17746}{17821}Jestli nevìøíš nièemu jinému...
{17821}{17897}Vìø tomuto...
{17897}{18934}Vìø nám.
{18934}{19010}Kde je ta...
{19010}{19161}ena, která ti dala ten klenot?
{19161}{19262}Náš èas zde konèí...
{19262}{19338}Èas Arwen konèí...
{19338}{19439}Nech ji jít!|Nech ji plout na západ.
{19439}{19515}Nech ji nést lásku k tobì|do neumírajících zemí,
{19515}{19591}které jsou vdy zelené...
{19591}{19692}Potom zùstane jen vzpomínkou.
{19692}{19768}Nenechám zde svou dceru zemøít.
{19768}{20046}-Zùstává, protoe má stále nadìji...|-Zùstává kvùli tobì! Patøí ke svému lidu.
{20046}{20198}Máš šanci na jinı ivot...
{20198}{20324}Daleko od války... alu... zoufalství...
{20324}{20400}Proè to øíkáš?
{20400}{20552}Já jsem smrtelnı, ty jsi elfka...
{20552}{20627}Byl to jen sen, Arwen...
{20627}{20880}Nic víc...
{20880}{21007}To patøí tobì.
{21007}{21108}Byl to dar...
{21108}{21209}Nech si to...
{21209}{21335}Pane?
{21335}{22018}Plude do zemí neumírajících,|se všemi, kteøí zùstali z jejího rodu.
{22018}{22094}Co se dìje?
{22094}{22953}-Eomere?|-Nejsem si jistı.
{22953}{23155}Prùzkumníci!
{23155}{23358}-Co se dìje, co vidíte?!|-Worgové, jsme napadeni!
{23358}{23408}Útok worgù!
{23408}{23888}-Všicni jezdci do èelakolony!|-Dìlej, pomo mi nahoru, já jsem jezdec!
{23888}{23964}Musíš vést lidi do Helmova lebu.|Pospìš si!
{23964}{24065}-Mùu bojovat!|-Ne!
{24065}{24166}Musíš to udìlat.|Pro mì.
{24166}{24268}Za mnou!
{24268}{24419}-Dìlej koni, dopøedu.|-Postavte se do kolony!
{24419}{25557}Zùstaòte spolu!
{25557}{26290}Do ùtoku!
{26290}{26416}Zemøeš pod mou sekerou, pojï!
{26416}{26871}Ten mìl bıt mùj!
{26871}{28818}Smradlavé stvoøení.
{28818}{28868}-Mami!|-Mami!
{28868}{28995}-Dìti!|-Mami!
{28995}{29298}Uvolnìte cestu pro Theodena!|Uvolnìte cestu králi!
{29298}{29450}Tak málo...|Tak málo se vás vrátilo.
{29450}{29551}Naši lidé jsou v bezpeèí.
{29551}{29652}Zaplatili jsme za to mnoha ivoty.
{29652}{29778}Má paní...
{29778}{29829}Pán Aragorn...
{29829}{29905}Kde je?
{29905}{30537}Padl...
{30537}{30613}Stáhnìte naše vojska za zeï!
{30613}{30688}Zataraste bránu|rozmístìte hlídky po okolí!
{30688}{30764}A co s tìmi co nemohou bojovat mùj pane?|eny a dìti?
{30764}{30865}Doveïte je do jeskyní!
{30865}{31042}Sarumanova ruka musí bıt dlouhá,|kdy si myslí, e na nás sem dosáhne.
{31042}{31118}Helmùv leb má jednu slabost...
{31118}{31270}Je celı z pevné skály,|a na malé kanály,
{31270}{31422}u jeho základù.
{31422}{31523}Jak...|Jak mùe oheò znièit kámen?
{31523}{31750}Jaké zaøízení mùe znièit zeï?
{31750}{31826}Kdy prolomíme zeï,|Helmùv leb padne.
{31826}{31927}I kdy ji prolomíme,|bude potøeba obrovské mnoství vojákù,
{31927}{32028}-Tisíce, aby porazili pevnost.|-Desítky tisíc...
{32028}{32433}Ale mùj pane, taková síla neexistuje!
{32433}{32534}Nová síla povstává!
{32534}{32736}Jjejí vítìzství ej na dosah!
{32736}{32787}Tuto noc...
{32787}{32913}Bude zemì pokryta krví Rohanu!
{32913}{32989}Pochodujte na Helmùv leb!
{32989}{33140}Nenechte nikoho naivu!
{33140}{33317}Do války!
{33317}{33368}Nebude ádnı úsvit...
{33368}{33874}Pro lidi.
{33874}{34101}-Podívejte, kouø na vıchodì!|-Poslední dobou z elezného pasu stále stoupá kouø.
{34101}{34303}-Z elezného pasu?|-Kdysi chodil Saruman po mém lese...
{34303}{34506}Ale teï má kovovou mysl.
{34506}{34784}-U ho nezajímají vìci, které rostou.|-Co to je?
{34784}{34834}To je Sarumanova armáda.
{34834}{35845}Válka zaèala.
{35845}{36781}Nech tì milost Valar ochrání.
{36781}{37463}Brego...
{37463}{37539}Arwen...
{37539}{37640}Ji je èas.|[Tollen i lu.]
{37640}{37716}Lodì odplouvají do Valinoru.|[I chair gwannar na Valannor.]
{37716}{37767}Jdi... dokud enní pøíliš pozdì.|[Si bado, no cirar.]
{37767}{37969}Vybrala jsem si.
{37969}{38095}On se nevrátí.
{38095}{38171}Proè tu ještì zùstáváš,|kdy u není ádná nadìje.
{38171}{38373}Nadìje tu stále je.
{38373}{38550}I kdy Aragorn pøeije tuto válku,|stejnì zùstanete oddìleni.
{38550}{38626}Jestlie bude Sauron poraen|a Aragorn se stane králem,
{38626}{38702}a vše v co doufáš se uskuteèní...
{38702}{38828}Budeš okoušet hoøkost smrtelnosti...
{38828}{39030}A u meèem,|nebo bìhem èasu, Aragorn zemøe...
{39030}{39283}A ty nebudeš nikdy mít klid...|Nebudeì moct ulehèit al nad jeho odchodem...
{39283}{39435}Zemøe,|bude jako obraz známıch lidskıch králù,
{39435}{39789}ve veliké slávì pøed úpadkem svìta...
{39789}{39915}Ale ty, má dcero...
{39915}{40016}Pøetrváš dál, v temnotì a pochybách...
{40016}{40193}Pøijde zimní noc beze hvìzd...
{40193}{40244}Zde budeš pøebıvat...
{40244}{40421}Pøipoutaná ke svému alu pod blednoucími stromy...
{40421}{40471}A se celı svìt zmìní
{40471}{40800}a dlouhé roky tvého ivota budou osamocenì proity...
{40800}{41002}Arwen...
{41002}{41078}Pro tebe tu nic není...
{41078}{41659}Jenom smrt.
{41659}{41786}Copak já také nemám tvou lásku?
{41786}{43126}Máš, mùj otèe|[Ie, im melin le, adar.]
{43126}{43201}[I amar prestar aen...]|Svìt se zmìnil.
{43201}{43277}[Han mathon ne nen...]|Cítím to ve vodì.
{43277}{43353}[Han mathon ne chae...]|Cítím to v zemi.
{43353}{43480}[A han noston ne gwilith...]|Cítím to ve vìtru.
{43480}{43581}Síla nepøítele roste...
{43581}{43808}Sauron vyuije své loutky Sarumana,|aby znièil lid Rohanu...
{43808}{43985}eleznı pas byl odpoután...
{43985}{44112}Oko Saurona se nyní otáèí ke Gondoru...
{44112}{44187}Poslednímu svobodnému království lidí...
{44187}{44390}Jeho válka v tìchto zemích pøijde náhle...
{44390}{44567}Cítí, e prsten je blízko...|Síla toho, kterı nese prsten, upadá...
{44567}{44718}Ve svém srdci, Frodo zaèíná rozumìt,
{44718}{44819}e úkol mu vezme ivot...
{44819}{44895}Ty to víš...
{44895}{44996}Pøedvìdìl jsi to...
{44996}{45199}To je riziko, které na sebe všichni bereme...
{45199}{45350}V shromaïujících se temnotách...|Síla prstenu roste...
{45350}{45477}Tvrdì pracuje na tom,|aby se vrátil zpìt do rukou lidí...
{45477}{45603}Lidí, kteøí jsou tak snadno|svedeni jeho mocí...
{45603}{45755}Mladému kapitánu Gondoru, staèí jen natáhnout ruku,|pøivlastnit si prsten...
{45755}{45881}A svìt padne...
{45881}{46109}Je teï blízko...|Tak blízko uskuteènìní svého cíle...
{46109}{46210}Protoe Sauron má sluebníky po celé této zemi...
{46210}{46361}a na konec svìta...
{46361}{46462}Èas elfù skonèil...
{46462}{46614}Necháme støedozemi svému osudu?
{46614}{46791}Necháme je stát samotné?
{46791}{46917}-Jaké jsou novinky?|-Naši prùzkumníci øíkají, e Saruman napadl Rohan.
{46917}{46993}Theodenùv lid utekl do Helmova lebu,
{46993}{47120}ale my se musíme soustøedit na vlastní hranice.|Faramire, orkové se pohybují.
{47120}{47170}Sauron sestavuje armádu.
{47170}{47271}-Vıchodòané prošli skrz Èernou bránu.|-Kolik?
{47271}{47347}Nìkolik tisíc, noví pøicházejí kadı den.
{47347}{47448}-Kdo hlídá øeku na severu?|-Poslali jsme 500 muù do Osgiliathu,
{47448}{47575}ale jestli na mìsto zaútoèí,|neudríme ho.
{47575}{47726}Saruman útoèí ze elezného pasu, Sauron z Mordoru...
{47726}{47802}Bitva bude pro lidi na obou frontách...
{47802}{47954}Gondor je slabı.|Sauron na nás brzy udeøí.
{47954}{48030}A udeøí tvrdì...
{48030}{48207}Ví teï, e nemáme sílu|je odrazit.
{48207}{48283}Spravte to!
{48283}{48485}Hobiti...
{48485}{48586}-Moji lidé mi øekli, e jste špióni orkù.|-Špióni?!
{48586}{48839}-Poèkejte chvilku!|-Jestli nejste špióni, kdo tedy jste?
{48839}{48915}Mluvte!
{48915}{48990}Jsme hobiti z Kraje...
{48990}{49117}-Já jsem Frodo Pytlík a to je Samvìd Køepelka.|-Tvùj osobní stráce?
{49117}{49167}Jeho zahradník.
{49167}{49268}A kde je váš plíící se pøítel...
{49268}{49420}Ten protáhlı tvor...|Nepøíjemného vzhledu?
{49420}{49572}Víc nás nebylo.
{49572}{49723}Odešli jsme z Roklinky se sedmi spoleèníky.
{49723}{49825}Jednoho jsme ztratili v Morii...
{49825}{49951}Dva byli mí krajané,|byl mezi námi také trpaslík, elf a dva lidé...
{49951}{50178}Aragorn, syn Arathornùv a Boromir z Gondoru.
{50178}{50355}-Jsi Boromirovım pøítelem?|-Ano...
{50355}{50558}Alespoò z mé strany...
{50558}{50659}Potom tì zarmoutí, e neije.
{50659}{50709}Neije?
{50709}{50810}-Jak, kdy?|-Jako jeden z jeho spoleèníkù,
{50810}{50987}doufal jsem, e mi to øekneš ty.
{50987}{51518}Byl to mùj bratr...
{51518}{51594}Kapitáne Faramire! 
{51594}{51948}Našli jsme toho tvora.
{51948}{52277}Musíš jít se mnou...|Teï.
{52277}{52706}Tam dole.
{52706}{53035}Vstup do zakázaného jezírka,|se trestá smrtí.
{53035}{53212}Èekají na mùj rozkaz.
{53212}{53262}Mám støílet?
{53262}{53364}Skály i jezírkou jsou krásné a chladné...
{53364}{53490}Mám tì rybo, chutná a sladká...
{53490}{53718}Mám tì rybo, chutná a sladká...
{53718}{53819}Poèkej...
{53819}{53894}Tento tvor je ke mnì pøipoután...
{53894}{54021}A já k nìmu.
{54021}{54173}On je naším prùvodcem.
{54173}{54552}Prosím!|nech mì jít k nìmu dolù!
{54552}{54602}Sméagole!
{54602}{54703}Pán je tu!
{54703}{54805}Pojï Sméagole!
{54805}{54956}Vìø pánovi!|Pojï!
{54956}{55057}Musíme jít teï...
{55057}{55209}Sméagole musíš vìøit pánovi!|Pojï za mnou! Tak pojï!
{55209}{55310}Pojï!
{55310}{55411}Pojï Sméagole.|Hodnı Sméagol.
{55411}{55563}Správnì.|Pojï.
{55563}{55613}Neubliujte mu!
{55613}{55689}Sméagole, neodporuj!|Sméagole, poslouchej mì!
{55689}{55993}Pane!
{55993}{56220}Ne!
{56220}{56321}Kam je vedeš?
{56321}{56372}Odpovìz!
{56372}{56549}Sméagole...
{56549}{56700}Proè pláèeš Sméagole?
{56700}{56852}Krutí lidé nám ubliují.|Pán nás podvedl!
{56852}{56953}Samozøejmì, e ano...
{56953}{57029}Øíkal jsem ti, e je podvodník...
{57029}{57130}Øíkal jsem ti e je falešnı...
{57130}{57307}-Pán je náš pøítel, náš pøítel.|-Pán nás podvedl!
{57307}{57408}Ne!|Není jeho vìc.
{57408}{57535}-Nech nás na pokoji!|-Prašiví malí hobiti!
{57535}{57661}-Ukradli nám ho!|-Ne, ne!
{57661}{57990}-Co ukradli?|-Mého miláška!
{57990}{58040}Musíme se odsud dostat.
{58040}{58141}Vy pùjdete.|Jdìte, teï!
{58141}{58242}Dokáete to!
{58242}{58318}Pouijte prsten, pane Frodo,|jako tenkrát.
{58318}{58369}Nasaïte si ho.
{58369}{58445}Zmizte.
{58445}{58546}Nemùu.
{58546}{58647}Mìl jsi pravdu Same...
{58647}{58723}Snail ses mi to øíct, ale...
{58723}{58824}Já...
{58824}{59001}omlouvám se...
{59001}{59102}Prsten mì zaèíná ovládat Same...
{59102}{59254}Kdy si ho nasadím...|Najde mì...
{59254}{59329}Uvidí...
{59329}{59506}Pane Frodo...
{59506}{59683}Take...|Tohle je odpovìï na hádanky.
{59683}{59961}Byli jste v divoèinì, e ano...|dva pùlèíci... a zástup lidí na mé vyzvání...
{59961}{60315}Prsten moci v mém dosahu...
{60315}{60442}Šance Faramira, kapitána Gondoru...
{60442}{61048}Aby ukázal své schopnosti...
{61048}{61175}Ne!
{61175}{61200}Pøestaò!
{61200}{61276}Nech ho na pokoji!
{61276}{61377}Copak tomu nerozumíš?!
{61377}{61428}On ho musí znièit!
{61428}{61503}Tam jdeme!|Do Mordoru!
{61503}{61579}K Ohnivé hoøe!
{61579}{61680}Osgiliath byl napaden.|ádají posily.
{61680}{61781}Prosím...|Je to takové beømeno...
{61781}{61883}Proè mu nepomùeš?
{61883}{61933}Kapitáne?
{61933}{62110}Pøipravte se na odchod.
{62110}{63728}Prsten pùjde do Gondoru.
{63728}{63981}Dobrá práce Brego, mùj pøíteli.|[Mae carnen, Brego, mellon nin.]
{63981}{64057}On se vrátil!
{64057}{64208}-On ije!|-Kde je! Kde je! Jdìte mi z cesty! Zabiju ho!
{64208}{64410}Jsi ten nejšastnìjší, nejchytøejší a nejlehkomyslnìjší mu,|jakého jsem kdy znal.
{64410}{64461}-Štìstí e jsi zpátky!|-Gimli...
{64461}{64714}-kde je král?|-Tamhle.
{64714}{64840}Jdeš pozdì.|[...dollen le.]
{64840}{65548}Vypadáš hroznì.
{65548}{65927}Dìkuji.|[Hannad le.]
{65927}{65978}Obrovskı pochod, øíkáš.
{65978}{66079}-Celı eleznı pas byl vaprázdnìn.|-Kolik?
{66079}{66180}Nejménì deset tisíc.
{66180}{66256}Deset tisíc?
{66256}{66357}To je armáda vypìstovaná pro jedinı úèel...
{66357}{66483}Aby znièila svìt lidí.
{66483}{66686}Budou tu za soumraku.
{66686}{66761}A pøijdou!
{66761}{66812}Chci kadého mue a chlapvce,|schopného dret zbraò,
{66812}{66964}aby byli pøipraveni na bitvu pøed západem slunce.
{66964}{67115}Pøesnì tak.
{67115}{67191}Budeme krıt cestu a bránu zeshora.
{67191}{67242}ádná armáda ještì neprolomila hradbu lebu,
{67242}{67343}ani nevstoupila do dvora!
{67343}{67469}Tohle není útok hloupıch orkù!|To jsou skurut-hai!
{67469}{67596}Jejich zbroj je mocná|štíty pevné.
{67596}{67697}Vybojoval jsem mnoho bitev, mistøe trpaslíku...
{67697}{67950}Vím jak ubránit svou vlastní pevnost.
{67950}{68025}Rozbijí se o tuto pevnost jako voda o skálu...
{68025}{68177}Sarumanovy hordy budou pálit a drancovat.|U jsme to vidìli.
{68177}{68278}Úroda mùe bıt znovu zaseta...
{68278}{68329}Domy znovu vybudovány...
{68329}{68455}Ale v tìchto hradbách...|Pøetrváme je.
{68455}{68556}Nepøišli znièit Rohanské vesnice,|pøišli znièit jeho lidi...
{68556}{68657}Do posledního dítìte!
{68657}{68708}Co chceš abych udìlal?
{68708}{68758}Podívej se na mé lidi.
{68758}{68860}Jejich odvaha visí na vlásku.
{68860}{68986}Jestli to má bıt náš konec,|udìlám z toho takovı konec,
{68986}{69138}kterı bude hoden zapamatování!
{69138}{69365}Vyšli jezdce pane!|Musíš volat o pomoc!
{69365}{69416}A kdo pøijde?
{69416}{69542}Elfové... trpaslíci...
{69542}{69618}Nemáme takové štìstí na pøátele jako ty.
{69618}{69694}Dávná spojenectví jsou mrtvá.
{69694}{69770}-Gondor odpoví.|-Gondor!
{69770}{69845}Kde byl Gondor,|kdy padla západní brázda?
{69845}{69947}Kde byl Gondor, kdy nás nepøátelé obklèovali?
{69947}{70048}Kde byl Gon...
{70048}{70149}Ne mùj pane Aragorne.
{70149}{70376}Jsme sami.
{70376}{70452}-Odveïte eny a dìti do jeskyní!|-Potøebujeme víc èasu, abychom dovezli zásoby...
{70452}{70553}Není víc èasu!|Máme pøed sebou válku!
{70553}{70756}Zabezpeète bránu.
{70756}{71034}My staøí se neúèastníme|válek mezi èarodìji a lidmi ji od pradávna.
{71034}{71362}Ale teï se má stát nìco,|co se nestalo po celı Vìk.
{71362}{71514}-Co to je?|-Shromádìní.
{71514}{72019}Shromádìní èeho?
{72019}{72424}Dub, Kaštan, Jasan.|Dobøe, dobøe, dobøe,  mnozí pøišli.
{72424}{72753}Nyní se musíme rozhodnout, jestli entové pùjdou do války.
{72753}{72803}Pojï!
{72803}{72904}Všichni do jeskyní!
{72904}{74067}Lidé poslouchejte!
{74067}{74118}Tu máš!
{74118}{74269}Na!|Dìlej!
{74269}{74345}-Kde jsou jezdci?|-To jsou všichni.
{74345}{74522}Farmáøi, pøevozníci, mladí chlapci...|To nejsou ádní vojáci.
{74522}{74724}-Mnoho z nich vidìlo pøíliš mnoho zim.|-Nebo pøíliš málo.
{74724}{74775}-Pojï.|-Podívejte se na nì!
{74775}{74950}Bojí se.|Vidím to v jejich oèích.
{74950}{75000}A mìli by...
{75000}{75125}Tøi sta...|Proti deseti tisícùm!
{75125}{75200}Mají vìtší nadìji se ubránit zde|ne v Edorasu...
{75200}{75325}Aragorne!|Oni nemohou vyhrát tuto bitvu.
{75325}{75575}-Všichni zemøou!|-Potom zemøu jako jeden z nich!
{75575}{75625}Nech ho jít.
{75625}{75725}Nech ho bıt.
{75725}{75950}Kadı vesnièan schopnı nést meè,|byl poslán do zbrojnice.
{75950}{76050}Pane?
{76050}{76200}Jak riskuji...
{76200}{76375}Jsi náš král, pane.
{76375}{76500}A ty vìøíš svému králi?
{76500}{76575}Tví lidé, pane...
{76575}{76825}Za tebou pùjdou, a je konec jakıkoli.
{76825}{77125}A je konec jakıkoli...
{77125}{77225}Kde je kùò a jezdec?
{77225}{77325}Kde je roh, kterı záøil?
{77325}{77475}Odešli, jako šeï hor.
{77475}{77625}Jako vítr na poli,
{77625}{77800}Dny odešly na západ.
{77800}{77850}Za hory,
{77850}{78100}Do stínu...
{78100}{78300}Jak se to mohlo stát?
{78300}{78800}Pøesuòte se na vnìjší zdi!
{78800}{79075}Dej mi svùj meè.
{79075}{79250}-Jak se jmenuješ?|-Halid, syn Hamy pane.
{79250}{79350}Lidé øíkají, e nepøeijeme noc.
{79350}{79850}Øíkají, e je to beznadìjné.
{79850}{80100}To jest dobrı meè...|Halide, synu Hamy.
{80100}{80725}Vdy je nadìje.
{80725}{80825}Vìøili jsme ti a doteï jsi nás nedovedl do záhuby.
{80825}{80875}Odpus mi.
{80875}{80975}Zoufal jsem zbyteènì.
{80975}{81125}Nemám co odpouštìt, Legolasi.
{81125}{81300}Je èas obléct si zbroj.
{81300}{81500}Je trochu tìsná okolo hrudníku.
{81500}{81675}To není roh orkù.
{81675}{81725}Pošli pro krále.
{81725}{82625}Otevøete bránu!|Otevøete bránu!
{82625}{82675}Jak je to moné?
{82675}{82775}Pøináším slovo od Elronda z Roklinky.
{82775}{82875}Kdysi existovalo spojenectví mezi lidmi a elfy.
{82875}{83025}V dávnıch dobách bojovali a umírali elfové a lidé bok po boku...
{83025}{83125}Pøišli jsme poctít toto spojenectví.
{83125}{83325}Vítej, Haldire.
{83325}{83500}Jsi nadmíru vítán.
{83500}{84450}Jsme hrdí, e mùeme znovu bojovat po boku lidí.
{84450}{84700}Mohl jsem si vybrat lepší místo.
{84700}{84900}Stále iju. Doufejme e to potrvá celou noc.
{84900}{84975}Tví pøátelé jsou s tebou, Aragorne.
{84975}{86525}Doufejme, e i oni pøeijí noc...
{86525}{86625}Buïte nelítostní...
{86625}{87550}Protoe nepøátelé jsou nelítostní!
{87550}{87650}-Co se tam dìje?!|-Mám ti to popsat?
{87650}{88675}nebo chceì abych ti pøinesl bednu?
{88675}{89275}Nestøílejte!
{89275}{89450}Tak to zaèíná...
{89450}{89700}Pøipravte se støílet!
{89700}{89750}Jejich zbroj je slabá u krku...
{89750}{89800}A pod ramenem.
{89800}{90025}Vypuset šípy!|[Hado i philinn!]
{90025}{90100}Zaènìte støílet!
{90100}{90275}Palte!|Palte!
{90275}{90550}Pøipravit!|Palte!
{90550}{91050}Pošlete je sem!|Dìlejte!
{91050}{91100}ebøíky!
{91100}{92125}Dobøe!
{92125}{92175}Legolasi!|U dva!
{92175}{92200}Já u jich mám sedmnáct!
{92200}{92450}Coe?!|Mì pøece nemùe porazit elf!
{92450}{93450}Devatenáct!
{93450}{93550}Smíšku.
{93550}{93825}Právì jsme odsouhlasili...
{93825}{93900}Ano?
{93900}{94050}Pøedstavil jsem vás radì entù.
{94050}{94225}A dohodli jsme se e nejste orkové.
{94225}{94300}To je dobrá novinky.
{94300}{94425}A co Saruman?|Dohodli jste se o nìm?
{94425}{94500}Nebuïte uspìchanı pane Smíšku.
{94500}{94600}Uspìchanı?|Naši pøátelé tam jsou.
{94600}{94675}Potøebují naši pomoc!
{94675}{94750}Nemohou tuhle válku bojovat sami!
{94750}{94875}Ó ano... |Ovlivòuje nás to všechny.
{94875}{95025}Ale musíš pochopit, mladı hobite,|e je potøeba hodnì èasu,
{95025}{95175}abychom nìco øekli starım entskım jazykem.
{95175}{95275}A my nedìláme nic,
{95275}{95475}pokud to nezabere|hodnì èasu.
{95475}{95550}Sedmnáct!|Osmnáct!
{95550}{96175}Devatenáct!|Dvacet!
{96175}{96975}To je všechno?|To je všechno co dokáeš vyèarovat Sarumane?
{96975}{97075}Zastøel ho, Legolasi!|[Dago han, Legolas!]
{97075}{98475}Zabij ho, zabij ho![Dago han!]
{98475}{98700}Zataraste bránu!
{98700}{98975}[Peter Jackson...  :-)]
{98975}{99225}Zadrte je!|Ustupte!
{99225}{99350}Aragorne!
{99350}{99550}Gimli!
{99550}{99650}Palte!|[Hado i philinn!]
{99650}{100600}Do útoku!|[Berio]
{100600}{100750}Entové nemohou zadret bouøi.
{100750}{100850}Musíme se o takovıch vìcech rozhodovat tak,|jako jsme to dìlali vdy.
{100850}{100925}Jak to mùe bıt vaše rozhodnutí?!
{100925}{101175}-Toto není naše válka.|-Ale jste souèástí tohoto svìta!
{101175}{101325}Nebo ne?
{101325}{101400}Musíte pomoci!|Prosím!
{101400}{101625}-Musíte nìco udìlat.|-Jsti mladı a odvánı Smíšku.
{101625}{101725}Ale tvùj údìl v tomto èase skonèil.
{101725}{102025}Vrate se domù.
{102025}{102125}Moná má Stromovous pravdu.|Nepatøíme sem Smíšku.
{102125}{102325}Je to pro nás pøíliš špatné.|Co vlastnì mùeme udìlat...
{102325}{102400}Máme Kraj.
{102400}{102525}Moná bychom mìli jít domù.
{102525}{102600}Ohnì elezného pasu se rozprostøou,
{102600}{102725}A lesy Tukonu a Bucklandu vzplanou.
{102725}{102800}A...
{102800}{102875}A všechno, co bylo kdysi|zelené a dobré na tomto svìtì, 
{102875}{102975}bude pryè.
{102975}{103525}Nebude Kraj Pipine.
{103525}{103625}Aragorne, Stáhnìte se do hradu!
{103625}{103750}Dostaò odtamtud své mue!
{103750}{103875}Do hradu!|[Na varad!]
{103875}{103950}Vrate se do hradu!|[Na varad!]
{103950}{104025}Haldire!
{104025}{104200}Do hradu!|[Na varad!]
{104200}{104650}Do hradu!|[Na varad!]
{104650}{105900}Haldire!
{105900}{106700}K bránì!|Taste meèe!
{106700}{106900}O moc déle u nevydríme!
{106900}{106975}-Zastavte je!|-Jak dlouho potøebujete?!
{106975}{107050}Tak dlouho jak mùete.
{107050}{107125}Gimli!
{107125}{107575}Stáhnìte se!|Zvednìte bránu!
{107575}{107650}Pojï!|Mùeme je dostat!
{107650}{107825}Je to dlouhá cesta.
{107825}{107900}-Postrè mì.|-Coe?
{107900}{108075}Nedoskoèím tak daleko,|take mì postrè!
{108075}{108600}-A... neøíkej to elfovi.|-To nemám v úmyslu.
{108600}{108650}Zpevnìte ty dveøe!
{108650}{108700}Z cesty!|Udìlejte barikádu!
{108700}{108825}Z cesty!
{108825}{110125}-Dejte to sem!|-Vıš!
{110125}{110275}Zamknìte bránu!
{110275}{110450}Gimli,Aragorne!|Uteète odtamtud!
{110450}{110550}Aragorne!
