{1}{1}}25
{25}{100}Stáhnìte všechny zpátky.
{100}{175}Stáhnìte je!
{175}{274}Zpátky!|Zpátky!
{274}{374}Kryjte se!|Stáhnìte se!
{374}{424}Zpátky!
{424}{474}-Zpátky!|-Pospìšte si!
{474}{524}Dovnitø!|Dostaòte je dovnitø!
{524}{873}Do hradu!
{873}{998}Nechám vás na západní hranici lesa.
{998}{1247}Odtamtud mùete jít na sever|do vašich domovù.
{1247}{1297}Poèkej!|Zastav se!
{1297}{1422}Zastav se!
{1422}{1497}Otoè se!
{1497}{1547}Otoè se!|Vezmi nás na jih!
{1547}{1696}Na jih...|Ale to vás dovede k eleznému pasu.
{1696}{1771}Ano.|Pøesnì.
{1771}{1846}Kdy pùjdeme na jih,|mùeme projít okolo Sarumana ani by si nás všiml.
{1846}{1921}Èím blíe jsme k nebezpeèí,|tím dál jsme od zranìní.
{1921}{2045}To je to poslední,|co oeèkává.
{2045}{2220}To mi nedává smysl...|Ale konec koncù jste velmi malí.
{2220}{2320}Moná máte pravdu.
{2320}{2420}Na jih tedy.
{2420}{2544}Pojïme malí krajané.
{2544}{2644}Vdycky chodím rád na jih. 
{2644}{2719}Nìjak mi to pøipomíná chození dolù z hor.
{2719}{2794}Zešílel jsi!|Chytí nás!
{2794}{2869}Nechytí.
{2869}{3093}Tentokrát ne.
{3093}{3143}Podívejte!
{3143}{3218}Osgiliath hoøí!
{3218}{3293}Mordor pøišel.
{3293}{3368}Prsten nezachrání Gondor!
{3368}{3442}Má jen sílu nièit.
{3442}{3542}Prosím!|Nechte mì jít!
{3542}{3692}Pospìšte si!
{3692}{3817}Faramire!|Musíš mì nechat jít!
{3817}{4340}Kdo ví,|moná si na nás ještì vzpomene.
{4340}{4440}Mnoho z tìchto stromù bylo mımi pøáteli.
{4440}{4615}-Stvoøení, která znám jako oøech a líska.|-Je mi líto Stromovousi.
{4615}{4739}Mìli své vlastní hlasy.
{4739}{4839}Saruman... 
{4839}{5263}Èarodìj by si to mìl líp rozmyslet.
{5263}{5488}Není ádná kletba v jazyce lidí, entù ani elfù,|která by mohla pomstít takovou zradu.
{5488}{5613}Já si to musím vyøídit se eleznım pasem.
{5613}{6236}Se skálou a kamenem.
{6236}{6311}Ano.
{6311}{6386}Pojïte moji pøátelé.
{6386}{6660}Entové jdou do války.|Je moné, e jdeme do své záhuby.
{6660}{7957}Poslední pochod entù.
{7957}{8032}Faramire!|Orkové majívıchodní bøeh.
{8032}{8082}Je jich pøíliš mnoho.
{8082}{8182}Do soumraku nás porazí.
{8182}{8257}Pane Frodo!
{8257}{8357}Volá ho Same.|Jeho oèi jsou skoro na mì. 
{8357}{8756}Budete v poøádku pane Frodo.|Všechno bude v poøádku.
{8756}{8830}Vezmìte je do mého stanu.
{8830}{8980}Øeknìte mu, e Faramir posílá mocnı dar.
{8980}{9080}Zbraò, která obrátí štìstí v této válce.
{9080}{9155}Chceš vìdìt co se stalo Boromirovi?!
{9155}{9230}Chceš vìdìt proè tvùj bratr zemøel?!
{9230}{9329}Chtìl vzít prsten Frodovi!|Poté co pøísahal, e ho bude chránit!
{9329}{9404}Proto zemøel!
{9404}{9479}Kvùli prstenu tvùj bratr zešílel!
{9479}{9778}Dávejte pozor!
{9778}{9878}Pane Frodo?
{9878}{10003}Jsou tu...
{10003}{10128}Pøicházejí...
{10128}{10602}-Nazgul!|-Schovejte se!
{10602}{10726}Ne!
{10726}{10826}Zùstaò tu, neukazuj se.
{10826}{11325}Skryjte se!
{11325}{11425}Hrad je dobyt.|To je konec.
{11425}{11525}Øekl jsi, e tato pevnost nikdy nepadne,|dokud ji budou tví lidé chránit!
{11525}{11649}Stále jí brání!|Umírají pøi tom!
{11649}{11899}Dostávají se dovnitø!
{11899}{12073}Copak není jiná cesta,|kudy by se eny a dìti dostaly z jeskynì?
{12073}{12148}Není jiná cesta?
{12148}{12248}Je jeden prùchod.|Vede do hot.
{12248}{12423}Ale en daleko.|Skurut-hai je pøíliš mnoho.
{12423}{12497}Pošli vzkaz enám a dìtem aby odešly|druhım prùchodem do hor!
{12497}{12622}-A zabarikáduj vstup!|-Tolik smrti...
{12622}{12822}Co mùe èlovìk udìlat proti|tak nièící nenávisti?
{12822}{12946}Vyjeï se mnou.
{12946}{13071}-Vyjeï jim na proti.|-Pro smrt a chválu.
{13071}{13146}Za Rohan.
{13146}{13196}Za tvùj lid.
{13196}{13370}Slunce vychází.
{13370}{13445}"Oèekávej mùj návrat,|za prvního svìtla pátého dne."
{13445}{13620}"Za úsvitu, hleï na vıchod."
{13620}{13720}Ano.
{13720}{13795}Ano.
{13795}{13944}Roh Helma elezného kladiva,|zazní v hlubinách!
{13944}{13994}Naposledy!
{13994}{14119}Ano!
{14119}{14767}Nech toto je hodina,|ve které spoleènì tasíme meèe.
{14767}{15990}Za lid Eorla!
{15990}{16214}Gandalf...
{16214}{16339}Král Theoden válèí sám.
{16339}{16563}Není sám.|Rohirrim!
{16563}{16613}Eomer...
{16613}{16688}Za krále!
{16688}{18858}Ano!
{18858}{19582}Zásah!|Pìknı zásah!
{19582}{19632}Mocnì zatáhnìte!
{19632}{20405}Uvolnìte skály!
{20405}{20604}Pipinie!|Dr se!
{20604}{21702}Ó ano, drte se hobiti!
{21702}{21952}Co to dìláte?
{21952}{23448}Kam jdete?!
{23448}{23548}To jsem já...
{23548}{23723}Váš Sam.
{23723}{24222}Nepoznáte svého Sama?!
{24222}{24321}Nedokáu to Same.
{24321}{24396}Já vím.
{24396}{24471}Nic není takové, jaké by mìlo bıt.
{24471}{24720}Vlastnì bychom tu vùbec nemìli bıt!
{24720}{24920}Ale jsme.
{24920}{24995}Je to jako ve velkıch pøíbìzích, pane Frodo.
{24995}{25169}Ty, které byly skuteènì dùleité,|byly plné temnoty a nebezpeèí.
{25169}{25394}A nìkdy jste ani nechtìl znát konec,|protoe jak by mohl bıt šastnı?!.
{25394}{25494}Jak se mohl svìt znovu stát takovım, jakı byl,|kdy se daøilo zlu?
{25494}{25668}Vítìzství!|Vítìzství!
{25668}{25768}Ale nakonec,|jen to jen pomíjivé...
{25768}{25893}Stín, i temnota musí oedjít...
{25893}{25968}Novı den pøijde...
{25968}{26117}A kdy slunce zaène svítit,|bude svítit jasnìji...
{26117}{26192}To byly pøíbìhy,|které s vámi zùstávaly...
{26192}{26242}Které nìco znamenaly...
{26242}{26317}I kdy jste byl pøíliš malı na to,|abyste rozumnìl proè...
{26317}{26417}Ale myslím si, pane Frodo,|e rozumím...
{26417}{26492}Teï vím...
{26492}{26666}Lidé z tìch pøíbìhù mìli mnoho pøíleitostí se vrátit,|ale neudìlali to...
{26666}{26741}Šli dál...
{26741}{26866}Protoe se mìli èeho dret...
{26866}{27215}Èeho se mùeme dret my, Same?
{27215}{27315}e na tomto svìtì je nìjaké donro, pane Frodo...
{27315}{28063}A stojí za to o nìj bojovat.
{28063}{28238}-Myslím e si koneènì vzájemnì rozumíme, Frodo Pytlíku.|-Znáš zákony našich zemí...
{28238}{28437}Zákony tvého otce.|Jestli je necháš jít, tvùj ivot bude ztracen.
{28437}{28537}Potom je ztracen.
{28537}{28861}Puste je!
{28861}{29161}Sauronova ztráta bude hrozivá.|Jeho pomsta rychlá.
{29161}{29260}Bitva o Helmùv leb skonèila.
{29260}{29460}Bitva o Støedozem právì zaèala.
{29460}{29585}Všechna naše nadìje|nyní leí na dvou malıch hobitech...
{29585}{29734}Kdesi v divoèinì.
{29734}{29834}Zajímalo by mì,|jestli nìkdy budeme v písních, nebo pøíbìzích.
{29834}{29884}Coe?
{29884}{29984}Zajímalo by mì, jestli budou lidé nìkdy øíkat:|"Poslechnìte si o Frodovi a prstenu."
{29984}{30059}A oni øeknou:|"Ano to je jeden z mıch nejoblíbenìjších pøíbìhù."
{30059}{30183}"Frodo byl opravdu odvánı, e ano tati?"|"Ano, mùj synu."
{30183}{30283}"Nejslavnìjší z hobitù|a to øíká mnoho."
{30283}{30408}Zapomnìli jste na jednu z nejdùleitìjších postav - Samvìda stateèného.
{30408}{30582}"Já chci slyšet víc o Samovi!"
{30582}{30682}"Frodo by se bez Sama daleko nedostal."
{30682}{30757}Pane Frodo.|Nemìl byste ertovat, 
{30757}{31056}-já jsem mluvil vánì.|-Já také.
{31056}{31231}Samvìd stateènı.
{31231}{31306}Sméagole!|Nebudeme na tebe èekat!
{31306}{31356}Pojï!
{31356}{31505}Pán...|Pán se o nás stará...
{31505}{31580}Pán by nám neublíil...
{31580}{31655}Pán porušil svùj slib!
{31655}{31780}Nepros Sméagola...|Chudák, chudák Sméagol...
{31780}{31880}Pán nás zradil!
{31880}{32029}Podlı, vychytralı, falešnı!|Zlomíme jeho špinavı malı krk!
{32029}{32104}Zabij ho!|Zabij ho!
{32104}{32154}Zabij je oba!
{32154}{32354}A potom si vezmeme miláška|a my budeme pánem!
{32354}{32503}Ale tlustı hobit, kdo ví,|jeho oèi jsou stále ve støehu.
{32503}{32703}Potom je vybodneme,|jeho oèi, take on se bude plazit.
{32703}{32828}Ano, ano, ano!
{32828}{32927}-Zabij je oba!|-Ano! -Ne, ne!
{32927}{33052}Je to pøíliš riskantní, pøíliš riskantní!
{33052}{33102}Kde je?|Kam zmizel?
{33102}{33152}Hej Glume?|Kde jsi?
{33152}{33351}-Smégole?|-Mohli bychom ji nechat aby to udìlala...
{33351}{33576}Ano! Ona by to mohla udìlat.|Ano milášku... Mohla by...
{33576}{33726}A potom si ho vezmeme,|a budou mrtví...
{33726}{33925}A budou mrtví.
{33925}{34025}Pojïte hobiti!|Ještì pøed sebou máme velkı kus cesty.
{34025}{34125}Sméagol vám ukáe cestu.|Pojïte za mnou.
